### PR TITLE
fix: Mysql invalid date breaks sync

### LINKED ISSUE #570: Sync failed with 0000-00-00 date values in MySQL db
## Environment

- Latest OLake v 0.2.6 + MySQL Connector

## Description
MySQL allows to store ZERO date/datetime like 0000-00-00 ( 0000-00-00 00:00:00)  or even more strange combinations like 2025-00-15.
See details here
https://dev.mysql.com/doc/refman/8.4/en/sql-mode.html#sqlmode_no_zero_in_date

It breaks sync process for entire table with error

error occurred while reading records: 
error occurred while waiting for connections: thread [ TABLE_NAME ]: 
failed to scan record data as map: failed to parse datetime from available formats: parsing time "0000-00-00 00:00:00": month out of range
 
## Expected behavior

It would be good to replace incorrect values to NULL or start of  epoch (January 1, 1970, at 00:00:00 UTC)

### PR DESCRIPTION
**Pull request by vaibhav-datazip**
# Description

Mysql supports invalid date addition in case invalid dates is allowed in db. Due to this when OLake detected a invalid date like
- 0000-00-00 (all 0)
- 2025-00-12 (month 0)
- 2025-07-00 (date 0)
- 2025-02-31 (invalid date of month)

the sync used to fail.

This PR fixes that issue and changes such invalid dates to start of epoch i.e. January 1, 1970, at 00:00:00 UTC

Fixes #570 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Postgres CDC, Full refresh, incremental
- [x] Mysql CDC, Full refresh, incremental
- [x] MongoDB CDC, Full refresh

# Screenshots or Recordings

## Documentation

- [ ] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [x] N/A (bug fix, refactor, or test changes only)

## Related PR's (If Any):

### CODE REVIEW

**Comment by ImDoubD-datazip** [comment]
haven't you added the fix for mongodb as well?

File: drivers/mysql/internal/mysql.go
Comment (ImDoubD-datazip) [inline drivers/mysql/internal/mysql.go:1]: there are various supported date formats in reformat.go. why haven't you done the changes there itself? there the issue of mongodb year 0 could also have been fixed.

File: drivers/mysql/internal/mysql.go [hunk 1]
```diff
@@ -219,9 +219,56 @@ func (m *MySQL) dataTypeConverter(value interface{}, columnType string) (interfa
...
+	if isDateTimeColumn(columnType) {
+		value = handleInvalidMySQLDates(value)
+	}
+
 	return typeutils.ReformatValue(olakeType, value)
 }
 
+// isDateTimeColumn checks if the column type is a date/datetime/timestamp type
+func isDateTimeColumn(columnType string) bool {
+	dateTimeTypes := []string{"date", "timestamp"}
```
Comment (ImDoubD-datazip) [inline drivers/mysql/internal/mysql.go]: there are types like timestamp_micro, timestamp_nano, are they not considered?

File: drivers/mysql/internal/mysql.go [hunk 2]
```diff
@@ -219,9 +219,56 @@ func (m *MySQL) dataTypeConverter(value interface{}, columnType string) (interfa
...
+	strValue := utils.ConvertToString(value)
+
+	isInvalidDate := func(value string) bool {
+		dateFormats := []string{
+			"2006-01-02",
+			"2006-01-02 15:04:05",
+			"2006-01-02T15:04:05",
+			"2006-01-02T15:04:05Z",
+			"2006-01-02T15:04:05.000000",
+			"2006-01-02T15:04:05.000000Z",
```
Comment (ImDoubD-datazip) [inline drivers/mysql/internal/mysql.go]: also if you have specified the formats here, then where are nano precisions. also this is redundant code.

File: drivers/mysql/internal/mysql.go [hunk 3]
```diff
@@ -219,9 +219,56 @@ func (m *MySQL) dataTypeConverter(value interface{}, columnType string) (interfa
...
+			if _, err := time.Parse(layout, value); err == nil {
+				return false
+			}
+		}
+		return true
+	}
+
+	if isInvalidDate(strValue) {
+		return time.Unix(0, 0).UTC()
+	}
```
Comment (ImDoubD-datazip) [inline drivers/mysql/internal/mysql.go]: what is the use of this function?

Comment (vaibhav-datazip) [reply drivers/mysql/internal/mysql.go]: return time of epoch start that is 1970

File: drivers/mysql/internal/mysql.go (hunk 1 above)
Comment (vaibhav-datazip) [reply drivers/mysql/internal/mysql.go]: if you will read the code below this you will find .

```
strings.Contains(strings.ToLower(columnType), dtType)
```

so if the string will contain timestamp or date , in all those cases this should work

File: drivers/mysql/internal/mysql.go
Comment (vaibhav-datazip) [reply drivers/mysql/internal/mysql.go:1]: so If you would see the previous commit, you will be able to see the changes were done in reformat.go only, but this caused an issue in oracle driver , also this change was only required in mysql hence moved it here.

apart from this , it was discussed on the Friday call that entering 0000 in monogdb and syncing is not causing any error.

**Comment by vaibhav-datazip** [comment]
> haven't you added the fix for mongodb as well?

as discussed on the Friday call ,
the test case reported by you, when we enter year as 0000 in mongodb and try to sync no error occurs and sync is completing successfully

similar closing comment is put by you in Issue #421 
Screenshot 2025-10-20 at 3 27 53 PM

File: drivers/mysql/internal/mysql.go (hunk 3 above)
Comment (ImDoubD-datazip) [reply drivers/mysql/internal/mysql.go]: Arey where it is getting called i mean

Comment (vaibhav-datazip) [reply drivers/mysql/internal/mysql.go]: no, I think you might have selected wrong lines in the comment or might have got confused.

 this is a if statement , that function is getting called in this block , here is that function which checks invalid date

```
isInvalidDate := func(value string) bool {
		dateFormats := []string{
			"2006-01-02",
			"2006-01-02 15:04:05",
			"2006-01-02T15:04:05",
			"2006-01-02T15:04:05Z",
			"2006-01-02T15:04:05.000000",
			"2006-01-02T15:04:05.000000Z",
		}
```

**Comment by ImDoubD-datazip** [comment]
> > haven't you added the fix for mongodb as well?
> 
> as discussed on the Friday call , the test case reported by you, when we enter year as 0000 in mongodb and try to sync no error occurs and sync is completing successfully
> 
> similar closing comment is put by you in Issue #421 Screenshot 2025-10-20 at 3 27 53 PM

this gives error during query. the sync is successful, but querying on it gives error. i though you were fixing that as well.

**Comment by vaibhav-datazip** [comment]
> this gives error during query. the sync is successful, but querying on it gives error. i though you were fixing that as well.

I think this is spark side error, because when we see the data in parquet it is fine.

File: drivers/mysql/internal/mysql.go (hunk 1 above)
Comment (ImDoubD-datazip) [reply drivers/mysql/internal/mysql.go]: ok. also can you use arrayContains function from utils.

File: drivers/mysql/internal/mysql.go (hunk 3 above)
Comment (ImDoubD-datazip) [reply drivers/mysql/internal/mysql.go]: oh it is inside the same function. i thought it was out. my bad.

File: drivers/mysql/internal/mysql.go (hunk 1 above)
Comment (vaibhav-datazip) [reply drivers/mysql/internal/mysql.go]: array contains can't be used here, its for strict comparison

File: drivers/mysql/internal/mysql.go [hunk 4]
```diff
@@ -219,9 +219,45 @@ func (m *MySQL) dataTypeConverter(value interface{}, columnType string) (interfa
 		return nil, typeutils.ErrNullValue
 	}
 	olakeType := typeutils.ExtractAndMapColumnType(columnType, mysqlTypeToDataTypes)
+
+	// Only apply invalid date handling to actual datetime/timestamp columns
+	if isDateTimeColumn(columnType) {
```
Comment (hash-data) [inline drivers/mysql/internal/mysql.go]: is it failing here?

**Comment by hash-data** [comment]
if we carefully check error is coming from the below  function, we can add a check there to verify the invalid date. It will be useful for all olake drivers
image

File: utils/typeutils/reformat.go [hunk 5]
```diff
@@ -205,16 +207,49 @@ func ReformatDate(v interface{}) (time.Time, error) {
...
+		logger.Warnf("Detected invalid year %d (year 0000 or negative). Converting to epoch start time (1970-01-01 00:00:00 UTC)", parsed.Year())
+		parsed = time.Unix(0, 0).UTC()
 	} else if parsed.Year() > 9999 {
 		parsed = parsed.AddDate(-(parsed.Year() - 9999), 0, 0)
 	}
 
 	return parsed, nil
 }
 
+func startsWithDatePattern(value string) bool {
```
Comment (ImDoubD-datazip) [inline utils/typeutils/reformat.go]: please make this inline function in the parseStringTimestamp.

File: utils/typeutils/reformat.go [hunk 6]
```diff
@@ -205,8 +207,11 @@ func ReformatDate(v interface{}) (time.Time, error) {
...
 	// manage year limit
 	// even after data being parsed if year doesn't lie in range [0,9999] it failed to get marshaled
-	if parsed.Year() < 0 {
-		parsed = parsed.AddDate(0-parsed.Year(), 0, 0)
+	// Check if year is 0000 (not supported by Spark)
+	// Spark only supports years from 1 to 9999, we are converting year 0000 to epoch start time
+	if parsed.Year() < 1 {
+		logger.Warnf("Detected invalid year %d (year 0000 or negative). Converting to epoch start time (1970-01-01 00:00:00 UTC)", parsed.Year())
+		parsed = time.Unix(0, 0).UTC()
 	} else if parsed.Year() > 9999 {
```
Comment (hash-data) [inline utils/typeutils/reformat.go:219]: Is it still required?

Comment (vaibhav-datazip) [reply utils/typeutils/reformat.go:219]: yes, because go parses it correctly , that's why sync was also getting completed successfully. but spark was unable to query it as it wasn't supported from there.

Comment (hash-data) [reply utils/typeutils/reformat.go:219]: can you add a comment for the same
