### PR TITLE
fix(postgres): validate replication slot against current database

### LINKED ISSUE #666: issue(postgres): check connection in postgres not check for database of replication slot
Description: 
check connection of postgres does not check for database of a particular replication slot. 
```
- create a replication slot with a  database db1
- try check connection with different database db2
- it is giving success, expected to give error that replication slot not exist in provided database.
```
Expected Behaviour: 
check connection should fail if replication slot is not related to that particular table. 

Extra Requirement: 
Can we check for the tables that are being selected in streams.json are being subscribed using publication slot or not. Fail sync if all selected streams not present in publication slot.

### PR DESCRIPTION
**Pull request by Ontiomacer**
# Description

This PR fixes an issue where the Postgres CDC connection check validated replication slot existence globally without verifying the database scope.

Previously, if a replication slot with the same name existed in a different database, the connection check would incorrectly succeed. This change ensures that the replication slot exists in the currently connected database before allowing CDC setup.

Fixes #666

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Local compilation verified using:
  - `go test ./drivers/postgres/internal -run TestDoesNotExist`
- [x] Short test mode attempted:
  - `go test -short ./drivers/postgres/...`

> Note: Full Postgres CDC integration and performance tests rely on Docker-based testcontainers and logical replication setup and were not run locally.

# Screenshots or Recordings

https://github.com/user-attachments/assets/ff7fe903-7c3f-45bd-b296-b478bb4d0646

## Documentation

- [x] N/A (bug fix, no user-facing documentation changes)

## Related PR's (If Any):

N/A

### CODE REVIEW

**Comment by Ontiomacer** [comment]
@nayanj98 
This PR addresses Issue #666 by scoping the replication slot existence check to the current database using `current_database()`.

Testing:
- Local compilation verified
- Heavy Postgres CDC integration/performance tests rely on Docker and logical replication setup and were not run locally

Looking forward to feedback.

**Comment by nayanj98** [comment]
@Ontiomacer Can you please rebase your PR to staging from master

**Comment by Ontiomacer** [comment]
@nayanj98 
Rebased the PR onto the latest `staging`. Please let me know if anything else is needed.

**Comment by nayanj98** [comment]
Screenshot 2026-01-02 at 3 22 39 PM
@Ontiomacer  It is still based on master. Please check again and rebase it to staging

**Comment by Ontiomacer** [comment]
alright can you check it now @nayanj98 ??

**Comment by nayanj98** [comment]
@Ontiomacer Looks good now. Assigning @ImDoubD-datazip to review your work

**Comment by nayanj98** [comment]
@Ontiomacer Can you please share a video of how you have tested your work. Makes it easier for us to understand if you are in right direction

**Comment by Ontiomacer** [comment]
A video for testing my fix?? @nayanj98 ?? should i submit it on slack via dm?
In the video i need to illustrate my fix how does it work ??

**Comment by nayanj98** [comment]
@Ontiomacer You can just add it here it will be easier for your reviewers to look at as well when they are assigned.

**Comment by nayanj98** [comment]
@Ontiomacer What you can do is record the entire process like setup your postgres as source and destination as well. Then you can show how your changes work by running a sync using OLake. As mentioned in the issue as you can check:
```
- create a replication slot with a  database db1
- try check connection with different database db2
- it is giving success, expected to give error that replication slot not exist in provided database.
```

You can kind of replicate these situations and show us by running the sync on OLake how these situations are handled.

File: drivers/postgres/internal/cdc.go [hunk 1]
```diff
@@ -101,7 +101,12 @@ func doesReplicationSlotExists(ctx context.Context, conn *sqlx.DB, slotName stri
 	var exists bool
 	err := conn.QueryRowContext(
 		ctx,
-		"SELECT EXISTS(Select 1 from pg_replication_slots where slot_name = $1)",
+		`SELECT EXISTS (
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go]: Hi @Ontiomacer , have you tested the exact case, i.e. in source config, pass the database where the replication slot exist and cdc sync is successful, and 2nd pass the database where the replication slot does not exist, and the sync fails? because for database where replication slot does not exist, database is not giving any error, but we need to give an error saying that replication slot does not exist for that database.

**Comment by Ontiomacer** [comment]
Hey @nayanj98

I reproduced the issue using the official olakego/source-postgres:latest image.

Setup

PostgreSQL instance with two databases: db1 and db2

Logical replication slot olake_slot created in db1

Observed behavior (current)
Running check against db2 succeeds even though:

pg_replication_slots.database = 'db1'

current_database() = 'db2'

This confirms the reported bug: replication slots are being validated globally instead of per-database.

Postgres-level validation:
SELECT EXISTS (
  SELECT 1
  FROM pg_replication_slots
  WHERE slot_name = 'olake_slot'
    AND database = current_database()
);
Connected to db1 → true

Connected to db2 → false

Fix
The patch enforces validation against current_database() when checking for replication slot existence.

With this change:

check succeeds for db1

check fails for db2

This behavior now correctly matches PostgreSQL semantics.
So should i create a video based on this workflow does it fulfill all the per-requisites?

File: drivers/postgres/internal/cdc.go (hunk 1 above)
Comment (Ontiomacer) [reply drivers/postgres/internal/cdc.go]: @ImDoubD-datazip 
I validated both cases at the source validation layer.
When database=db1 (replication slot exists in db1), check succeeds and CDC proceeds normally.
When database=db2 (replication slot exists only in db1), check fails after this change.
Since sync internally calls the same validation before starting CDC, a failing check prevents CDC from starting, so sync fails early as expected.
This ensures CDC can only start when the replication slot belongs to the configured database.

Comment (ImDoubD-datazip) [reply drivers/postgres/internal/cdc.go]: We need to give an error here, stating that replication slot is not of the current database.

Comment (Ontiomacer) [reply drivers/postgres/internal/cdc.go]: Hi @ImDoubD-datazip ,

I’ve pushed an update addressing this.

The logic now explicitly returns an error when the replication slot does not belong to the configured database (i.e. database != current_database()), instead of silently returning exists=false.

Behavior now:

database=db1 (slot exists in db1) → check / sync succeeds

database=db2 (slot exists only in db1) → check / sync fails with a clear error message

Could you please re-review the latest commit and confirm if this meets the expectation?

**Comment by nayanj98** [comment]
@ImDoubD-datazip Does the above approach look sound?

File: drivers/postgres/internal/cdc.go [hunk 2]
```diff
@@ -101,14 +101,27 @@ func doesReplicationSlotExists(ctx context.Context, conn *sqlx.DB, slotName stri
...
 	if err != nil {
 		return false, err
 	}
 
-	return exists, validateReplicationSlot(ctx, conn, slotName, publication)
+	if !exists {
+		return false, fmt.Errorf(
+			"replication slot '%s' does not exist in the current database '%s'",
+			slotName,
+			conn.DriverName(), // or database name if available in config
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go]: we have to provide the database name only, nothing else. conn.DriverName returns postgres driver name which is being used i.e pgx. pass it from the config, in setup in postgres.go where this function is called

**Comment by ImDoubD-datazip** [comment]
Hi @Ontiomacer reviewed again.

File: drivers/postgres/internal/cdc.go (hunk 2 above)
Comment (Ontiomacer) [reply drivers/postgres/internal/cdc.go]: Hi @ImDoubD-datazip,  
I’ve updated the implementation to pass the actual database name from config into the error message and pushed the changes.  
Could you please take another look when you get a chance?

**Comment by Ontiomacer** [comment]
@ImDoubD-datazip can you check on the latest implemented changes..?

File: drivers/postgres/internal/postgres.go [hunk 3]
```diff
@@ -114,8 +114,15 @@ func (p *Postgres) Setup(ctx context.Context) error {
...
-		exists, err := doesReplicationSlotExists(ctx, pgClient, cdc.ReplicationSlot, cdc.Publication)
+		dbName := strings.TrimPrefix(p.config.Connection.Path, "/")
+
+		exists, err := doesReplicationSlotExists(
+			ctx,
+			pgClient,
+			cdc.ReplicationSlot,
+			cdc.Publication,
+			dbName,
+		)
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/postgres.go]: keep it in single line

File: drivers/postgres/internal/cdc.go [hunk 4]
```diff
@@ -97,18 +97,37 @@ func (p *Postgres) PostCDC(ctx context.Context, _ types.StreamInterface, noErr b
...
 		return false, err
 	}
 
-	return exists, validateReplicationSlot(ctx, conn, slotName, publication)
+	if !exists {
+		return false, fmt.Errorf(
+			"replication slot '%s' does not exist in the current database '%s'",
+			slotName,
+			database,
+		)
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go]: keep this in single line

File: drivers/postgres/internal/cdc.go [hunk 5]
```diff
@@ -97,18 +97,37 @@ func (p *Postgres) PostCDC(ctx context.Context, _ types.StreamInterface, noErr b
...
 }
 
-func doesReplicationSlotExists(ctx context.Context, conn *sqlx.DB, slotName string, publication string) (bool, error) {
+func doesReplicationSlotExists(
+	ctx context.Context,
+	conn *sqlx.DB,
+	slotName string,
+	publication string,
+	database string,
+) (bool, error) {
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go]: keep this in single line

**Comment by ImDoubD-datazip** [comment]
@Ontiomacer reviewed again.

File: drivers/postgres/internal/postgres.go [hunk 6]
```diff
@@ -114,8 +114,15 @@ func (p *Postgres) Setup(ctx context.Context) error {
 		}
 
 		logger.Infof("CDC initial wait time set to: %d", cdc.InitialWaitTime)
-
-		exists, err := doesReplicationSlotExists(ctx, pgClient, cdc.ReplicationSlot, cdc.Publication)
+		dbName := strings.TrimPrefix(p.config.Connection.Path, "/")
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/postgres.go]: in config there is database. take that itself.

File: drivers/postgres/internal/postgres.go [hunk 7]
```diff
@@ -114,8 +114,15 @@ func (p *Postgres) Setup(ctx context.Context) error {
...
+
+		exists, err := doesReplicationSlotExists(
+			ctx,
+			pgClient,
+			cdc.ReplicationSlot,
+			cdc.Publication,
+			dbName,
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/postgres.go]: pass here config database itself.

File: drivers/postgres/internal/cdc.go
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go:1]: also have you tested this? like have you run the postgres cdc sync? can you share a video of how this postgres sync fails on different database where the replication slot does not exists.

**Comment by nayanj98** [comment]
@Ontiomacer Can you please create a post a video as well about your work. I have explained above what the video can consist

**Comment by Ontiomacer** [comment]
Hey @ImDoubD-datazip 
Addressed all review comments:

Validation now errors when replication slot does not belong to the configured database

Uses config.database directly

Simplified control flow per style feedback

Tested both cases locally:

slot exists in configured DB → success

slot exists in different DB → explicit failure

**Comment by Ontiomacer** [comment]
Any updates on my latest fix/workflow @ImDoubD-datazip correct or incorrect.

**Comment by Akshay-datazip** [comment]
> Any updates on my latest fix/workflow @ImDoubD-datazip correct or incorrect.

Hi can you provide us the video as stated above by @nayanj98

**Comment by Ontiomacer** [comment]
Hey @Akshay-datazip did you check my pr description? Does that full fill your video requirements?

File: drivers/postgres/internal/cdc.go [hunk 8]
```diff
@@ -97,18 +97,27 @@ func (p *Postgres) PostCDC(ctx context.Context, _ types.StreamInterface, noErr b
...
+		   WHERE slot_name = $1
+		     AND database = current_database()
+		 )`,
 		slotName,
 	).Scan(&exists)
 	if err != nil {
 		return false, err
 	}
 
-	return exists, validateReplicationSlot(ctx, conn, slotName, publication)
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go:111]: return this only.

File: drivers/postgres/internal/postgres.go [hunk 9]
```diff
@@ -115,17 +115,15 @@ func (p *Postgres) Setup(ctx context.Context) error {
...
+		_, err := doesReplicationSlotExists(ctx, pgClient, cdc.ReplicationSlot, cdc.Publication, p.config.Database)
+
 		if err != nil {
 			if strings.Contains(err.Error(), "sql: no rows in result set") {
 				err = fmt.Errorf("no record found")
 			}
 			return fmt.Errorf("failed to validate cdc configuration for slot %s: %s", cdc.ReplicationSlot, err)
 		}
 
-		if !exists {
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/postgres.go:126]: do this check here, not in the doesReplicationSlotExists function.

File: drivers/postgres/internal/cdc.go [hunk 10]
```diff
@@ -97,18 +97,27 @@ func (p *Postgres) PostCDC(ctx context.Context, _ types.StreamInterface, noErr b
...
+	if !exists {
+		return false, fmt.Errorf("replication slot '%s' does not exist in the current database '%s'", slotName, database)
+	}
+
+	return true, validateReplicationSlot(ctx, conn, slotName, publication)
```
Comment (ImDoubD-datazip) [inline drivers/postgres/internal/cdc.go]: no need of this.

**Review by ImDoubD-datazip — APPROVED** [review]

**Comment by Ontiomacer** [comment]
Thanks @ImDoubD-datazip and Ankit Sharma for merging this. Just wanted to confirm—are there any additional changes or follow-ups you’d like me to work on? Also, regarding the changes that were previously requested during review, is everything addressed to your satisfaction now?

**Comment by Akshay-datazip** [comment]
> Thanks @ImDoubD-datazip and Ankit Sharma for merging this. Just wanted to confirm—are there any additional changes or follow-ups you’d like me to work on? Also, regarding the changes that were previously requested during review, is everything addressed to your satisfaction now?

Hey @Ontiomacer 
Congrats and thank you for your contribution! 
Your Pull Request was one of the first to be merged under the SWOC program, and we really appreciate the effort you put in.

We have more issues listed on GitHub under the SWOC tags feel free to pick those up if you’re interested. If your upcoming updates continue to be strong and consistent, we’ll add you to our private channel as well that includes th bounties

Keep up the great work !

**Comment by Ontiomacer** [comment]
@Akshay-datazip On it..!!

**Comment by ImDoubD-datazip** [comment]
merged
