### PR TITLE
fix: unsigned integer overflow

### LINKED ISSUE #842: Incorrect data type mapping for MySQL for INT UNSGINED
## Description
Now MySQL INT UNSIGNED is mapped to int type. Its causing overflowing for value that are bigger than 2147483647 (max for INT).
In MySQL value 3349714808 is saved in Parquet as -945252488.

## Expected behavior
INT UNSGINED type should be mapped to bigint to properly save large values.

### PR DESCRIPTION
**Pull request by saksham-datazip**
# Description

This PR fixes incorrect handling of UNSIGNED numeric columns in MySQL, which was causing integer overflow issues.

The go-mysql binlog parser returns all integers as signed types, leading to overflow and incorrect (often negative) values for large UNSIGNED data. This change reinterprets such values as their correct unsigned types before processing, ensuring accurate CDC output.

Fixes #842 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I created a table containing different datatype and for unsigned int32 ,the data parsed was negative.
- [x] Scenario A: Created a table with multiple data types, including UNSIGNED INT32. Performed initial sync, then applied updates on the table and triggered CDC. Verified that previously negative values are now correctly interpreted and CDC output is accurate after the fix.

- [x] Scenario B: Performed initial sync using the previous version (where the issue existed), then upgraded to the new version and applied further updates. Verified that new CDC events correctly reflect unsigned values, ensuring backward compatibility for existing pipelines.

# Screenshots or Recordings
Input table format :-
image
Recreated Issue after versioning and cdc update:-
image

## Documentation

- [ ] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [x] N/A (bug fix, refactor, or test changes only)

## Related PR's (If Any):
N/A

### CODE REVIEW

File: drivers/mysql/internal/datatype_conversion.go [hunk 1]
```diff
@@ -10,10 +10,11 @@ var mysqlTypeToDataTypes = map[string]types.DataType{
 	"mediumint":          types.Int32,
 	"int":                types.Int32,
 	"integer":            types.Int32,
-	"unsigned int":       types.Int32,
+	"unsigned int":       types.Int64,
 	"unsigned smallint":  types.Int32,
 	"unsigned tinyint":   types.Int32,
 	"unsigned mediumint": types.Int32,
+	"unsigned bigint":    types.Int64,
```
Comment (vikaxsh) [inline drivers/mysql/internal/datatype_conversion.go:18]: how int64 will handle this value?
Signed max = 2^63-1
Unsigned max = 2^64-1

File: pkg/binlog/filter.go [hunk 2]
```diff
@@ -140,7 +141,22 @@ func convertRowToMap(row []interface{}, tableMap *replication.TableMapEvent, col
...
+			return "UNSIGNED TINYINT"
+		case mysql.MYSQL_TYPE_SHORT:
+			return "UNSIGNED SMALLINT"
+		case mysql.MYSQL_TYPE_INT24:
+			return "UNSIGNED MEDIUMINT"
+		case mysql.MYSQL_TYPE_LONG:
+			return "UNSIGNED INT"
+		case mysql.MYSQL_TYPE_LONGLONG:
+			return "UNSIGNED BIGINT"
+		}
```
Comment (vikaxsh) [inline pkg/binlog/filter.go]: consider moving unsigned check inside existing condiitons

File: drivers/mysql/internal/datatype_conversion.go (hunk 1 above)
Comment (saksham-datazip) [reply drivers/mysql/internal/datatype_conversion.go:18]: it has been discussed we are not handling this case

File: drivers/mysql/internal/mysql.go [hunk 3]
```diff
@@ -225,6 +225,10 @@ func (m *MySQL) ProduceSchema(ctx context.Context, streamName string) (*types.St
 			}
 			stream.WithCursorField(columnName)
 			datatype := types.Unknown
+			isInteger := strings.Contains(strings.ToLower(dataType), "int") || strings.EqualFold(dataType, "integer")
```
Comment (vishalm0509) [inline drivers/mysql/internal/mysql.go]: Here, `strings.Contains` will handle the case for `strings.EqualFold(dataType, "integer")` as well. 

Do we need both ?

File: drivers/mysql/internal/mysql.go [hunk 4]
```diff
@@ -271,6 +275,36 @@ func (m *MySQL) dataTypeConverter(value interface{}, columnType string) (interfa
...
+			if v, ok := value.(int64); ok {
+				value = uint64(v)
+			}
+		}
+	} else {
+		// Version < 4 legacy behavior: map all unsigned types to types.Int32
+		if strings.Contains(strings.ToLower(columnType), "unsigned") {
+			columnType = "int"
+		}
+	}
```
Comment (vishalm0509) [inline drivers/mysql/internal/mysql.go:301]: Earlier, `unsigned bigint` were processed as `BIGINT`, now we are mapping to `INT`. 

Instead of mapping to int, can we just remove the prefix "unsigned "

```go
if strings.HasPrefix(columnType, "unsigned ") {
	columnType = strings.TrimSpace(strings.TrimPrefix(columnType, "unsigned "))
}
```

--- 

In `filter.go`, Now we are setting `UNSIGNED BIGINT` if unsigned is `true` now as that passed through the datatype converted for old jobs, and they are mapped to `int`, but earlier they were mapped to bigint.

File: pkg/binlog/filter.go (hunk 2 above)
Comment (saksham-datazip) [reply pkg/binlog/filter.go]: solved

File: drivers/mysql/internal/mysql.go (hunk 3 above)
Comment (saksham-datazip) [reply drivers/mysql/internal/mysql.go]: solved

File: drivers/mysql/internal/mysql.go [hunk 5]
```diff
@@ -271,6 +271,35 @@ func (m *MySQL) dataTypeConverter(value interface{}, columnType string) (interfa
...
+		switch strings.ToLower(columnType) {
+		case "unsigned tinyint":
+			if v, ok := value.(int8); ok {
+				value = uint8(v)
+			}
+		case "unsigned smallint":
+			if v, ok := value.(int16); ok {
+				value = uint16(v)
+			}
+		case "unsigned mediumint", "unsigned int":
```
Comment (vishalm0509) [inline drivers/mysql/internal/mysql.go]: add `unsigned_integer` here
