### PR TITLE
fix: remove SCN dependency in Oracle and ensure consistent cursor values during backfill

### LINKED ISSUE #450: Backfill chunks use separate transactions, risking inconsistent cursor values during incremental syncs
## Description
When running an incremental sync for the first time, Olake triggers a backfill before incremental to store initial cursor values.
Currently, in all drivers (Postgres, MySQL, Oracle), ChunkIterator opens a new transaction for each chunk.

This means that:
- Each SELECT * for a chunk runs under a different transaction.
- If new data is inserted/updated between chunk reads, incorrect chunk value is saved in state.
- The incremental sync may start from an incorrect cursor state.

Example scenario:
Backfill splits a table into 3 chunks with initial max cursor values:
```
Chunk 1: max cursor = 1  
Chunk 2: max cursor = 4  
Chunk 3: max cursor = 6  
```
While processing Chunk 2, some row from Chunk 1 changes so that its  max cursor is now 9, more changes happen in chunk 3 at same time so that its max cursor is now 10.
At the end of backfill, the saved cursor in state becomes 10 (the highest seen across all chunks).
Incremental sync will start from cursor >= 10, skipping rows that had cursor values between 6–9.

## Steps to reproduce
1. Start a first-time incremental sync on a table.
2. Observe that in backfill.go, for each chunk, driver. ChunkIterator starts its own transaction.
3. While backfill is running, update data in the table between chunk queries (specially for the cursor fields set).

Result: final saved cursor value might be different than what it was supposed to be, which might result in some rows being skipped.

## Expected behavior

Backfill for a stream should run all chunk queries against a single stable snapshot of the source so that:
- Cursor values reflect the state at the start of backfill.
- No data is skipped during the subsequent incremental sync.

## Actual behavior

each select query has different transaction, which might cause skipping some data during incremental

### PR DESCRIPTION
**Pull request by vaibhav-datazip**
# Description

- Removed SCN dependency from the Oracle driver. SCN is active only for ~15 minutes by default, and extending redo log retention increases database load.
- Fixed cursor value handling to ensure consistency. Previously, the cursor was not guaranteed to be stable, which could cause skipped records during incremental sync. Now, the initial maximum cursor is determined before chunking begins across all drivers.

Fixes #450

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Incremental mode tests using all drivers
- [x] Incremental sync runs with different cursor field types:
  - [x] Timestamp (with and without timezone)
  - [x] String
  - [x] Boolean
  - [x] Int
  - [x] Float

## Documentation

- [ ] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [x] N/A (bug fix, refactor, or test changes only)

### CODE REVIEW

File: drivers/abstract/incremental.go [hunk 1]
```diff
@@ -77,8 +76,8 @@ func (a *AbstractDriver) Incremental(ctx context.Context, pool *destination.Writ
 
 					// set state (no comparison)
```
Comment (hash-data) [inline drivers/abstract/incremental.go:95]: TODO: make incremental streams to run parallel

File: drivers/abstract/backfill.go [hunk 2]
```diff
@@ -65,21 +79,6 @@ func (a *AbstractDriver) Backfill(ctx context.Context, backfilledStreams chan st
...
-						return
-					}
-					if typeutils.Compare(maxPrimaryCursorValue, prevPrimaryCursor) == 1 {
-						a.state.SetCursor(stream.Self(), primaryCursor, a.reformatCursorValue(maxPrimaryCursorValue))
-					}
-					if typeutils.Compare(maxSecondaryCursorValue, prevSecondaryCursor) == 1 {
-						a.state.SetCursor(stream.Self(), secondaryCursor, a.reformatCursorValue(maxSecondaryCursorValue))
-					}
-				}
 			} else {
```
Comment (hash-data) [inline drivers/abstract/backfill.go:66]: we can remove logic in chunk iterator as well

File: drivers/abstract/incremental.go [hunk 3]
```diff
@@ -135,11 +134,3 @@ func (a *AbstractDriver) getMaxIncrementCursorFromData(primaryCursor, secondaryC
 	}
 	return primaryCursorValue, secondaryCursorValue
 }
-
-// reformatCursorValue is used to make time format consistent in state (Removing timezone info)
```
Comment (hash-data) [inline drivers/abstract/incremental.go:139]: any reason for moving it ?

File: drivers/mongodb/internal/backfill.go [hunk 4]
```diff
@@ -476,3 +476,55 @@ func isObjectID(ctx context.Context, collection *mongo.Collection) (bool, error)
...
+				return result["maxPrimaryCursor"], maxSecondaryCursor, nil
+			}
+		}
+		return result["maxPrimaryCursor"], nil, nil
+	}
+
+	if err := cursor.Err(); err != nil {
+		return nil, nil, fmt.Errorf("cursor error: %s", err)
+	}
+	return nil, nil, fmt.Errorf("no documents found")
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: this will fail the sync on 0 records which is not expected.

File: pkg/jdbc/jdbc.go [hunk 5]
```diff
@@ -626,3 +620,46 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
 
 	return incrementalQuery, queryArgs, nil
 }
+
+func MaxCursorSetter(ctx context.Context, opts IncrementalConditionOptions) (any, any, error) {
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]:
```suggestion
func GetMaxCursorValue(ctx context.Context, opts IncrementalConditionOptions) (any, any, error) {
```

File: pkg/jdbc/jdbc.go [hunk 6]
```diff
@@ -626,3 +620,46 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+	primaryCursor, secondaryCursor := opts.Stream.Cursor()
+	quotedTable := QuoteTable(opts.Stream.Namespace(), opts.Stream.Name(), opts.Driver)
+
+	filter, err := SQLFilter(opts.Stream, string(opts.Driver))
+	if err != nil {
+		return nil, nil, fmt.Errorf("failed to parse stream filter: %s", err)
+	}
+	filterClause := utils.Ternary(filter == "", "", " WHERE ("+filter+")").(string)
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]: use fmt.Sprintf

File: pkg/jdbc/jdbc.go [hunk 7]
```diff
@@ -626,3 +620,46 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+			return nil, nil, fmt.Errorf("failed to scan the cursor values: %s", err)
+		}
+		maxSecondaryCursorValue = bytesConverter(maxSecondaryCursorValue)
+	} else {
+		err = opts.Client.QueryRowContext(ctx, cursorValueQuery).Scan(&maxPrimaryCursorValue)
+		if err != nil {
+			return nil, nil, fmt.Errorf("failed to scan primary cursor value: %s", err)
+		}
+	}
+	return bytesConverter(maxPrimaryCursorValue), maxSecondaryCursorValue, nil
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go:664]: why byte convertor not used for secondary cursor value?

Comment (vaibhav-datazip) [reply pkg/jdbc/jdbc.go:664]: byte conversion of secondary cursor value is done inside the if block

File: drivers/abstract/incremental.go (hunk 3 above)
Comment (vaibhav-datazip) [reply drivers/abstract/incremental.go:139]: reverted back

File: drivers/mongodb/internal/backfill.go [hunk 8]
```diff
@@ -481,6 +481,58 @@ func isObjectID(ctx context.Context, collection *mongo.Collection) (bool, error)
...
+			Value: bson.D{{Key: "$max", Value: "$" + secondaryCursor}},
+		})
+	}
+
+	pipeline := mongo.Pipeline{
+		{{Key: "$match", Value: filter}},
+		{{Key: "$group", Value: groupStage}},
+	}
+
+	cursor, err := collection.Aggregate(ctx, pipeline)
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: can we use simple fineOne function ?

File: drivers/mongodb/internal/backfill.go [hunk 9]
```diff
@@ -481,6 +481,58 @@ func isObjectID(ctx context.Context, collection *mongo.Collection) (bool, error)
...
+			}
+		}
+		return result["maxPrimaryCursor"], nil, nil
+	}
+
+	if err := cursor.Err(); err != nil {
+		return nil, nil, fmt.Errorf("cursor error: %s", err)
+	}
+	logger.Warnf("No documents found for stream: %s", stream.ID())
+	return nil, nil, nil
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]:
```suggestion
	return nil, nil, cursor.Err()
```
add nil check on calling function

File: drivers/mysql/internal/backfill.go [hunk 10]
```diff
@@ -188,3 +188,17 @@ func (m *MySQL) getTableExtremes(stream types.StreamInterface, pkColumns []strin
 	err = tx.QueryRow(query).Scan(&min, &max)
 	return min, max, err
 }
+
+func (m *MySQL) FetchMaxCursorValues(ctx context.Context, stream types.StreamInterface) (any, any, error) {
+	opts := jdbc.IncrementalConditionOptions{
```
Comment (hash-data) [inline drivers/mysql/internal/backfill.go]: making incremental condition option is not feasible, as only thing required is driver and stream

File: pkg/jdbc/jdbc.go [hunk 11]
```diff
@@ -626,3 +620,46 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+func GetMaxCursorValues(ctx context.Context, opts IncrementalConditionOptions) (any, any, error) {
+	primaryCursor, secondaryCursor := opts.Stream.Cursor()
+	quotedTable := QuoteTable(opts.Stream.Namespace(), opts.Stream.Name(), opts.Driver)
+
+	filter, err := SQLFilter(opts.Stream, string(opts.Driver))
+	if err != nil {
+		return nil, nil, fmt.Errorf("failed to parse stream filter: %s", err)
+	}
+	filterClause := utils.Ternary(filter == "", "", fmt.Sprintf(" WHERE (%s)", filter)).(string)
+
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go:633]: we are using '(' any reason?, are we able to add other sql terms in it or not like limit etc?

File: drivers/mongodb/internal/backfill.go [hunk 12]
```diff
@@ -472,6 +472,46 @@ func isObjectID(ctx context.Context, collection *mongo.Collection) (bool, error)
...
+	filter, err := buildFilter(stream)
+	if err != nil {
+		return nil, nil, fmt.Errorf("failed to build filter: %s", err)
+	}
+
+	findMaxCursor := func(maxCursor string) (any, error) {
+		if maxCursor == "" {
+			return nil, nil
+		}
+		opts := options.FindOne().SetSort(bson.D{{Key: maxCursor, Value: -1}})
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: is there no way other then sort of data?

File: pkg/jdbc/jdbc.go [hunk 13]
```diff
@@ -21,7 +21,7 @@ func QuoteIdentifier(identifier string, driver constants.DriverType) string {
 	case constants.MySQL:
 		return fmt.Sprintf("`%s`", identifier)
 	case constants.Postgres:
-		return fmt.Sprintf(`"%s"`, identifier)
+		return fmt.Sprintf("%q", identifier)
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go:24]: any reason?

Comment (vaibhav-datazip) [reply pkg/jdbc/jdbc.go:24]: "%s" is same as %q, and we are doing similar thing in oracle.

this was left out earlier

File: drivers/mongodb/internal/backfill.go (hunk 12 above)
Comment (vaibhav-datazip) [reply drivers/mongodb/internal/backfill.go]: can switch to the previous query which was being used in earlier commits .

File: pkg/jdbc/jdbc.go (hunk 13 above)
Comment (hash-data) [reply pkg/jdbc/jdbc.go:24]: then in mysql ?

Comment (vaibhav-datazip) [reply pkg/jdbc/jdbc.go:24]: in mysql parameters need to be put in between `\` \`` whereas for postgres and oracle its " "

File: drivers/mongodb/internal/backfill.go [hunk 14]
```diff
@@ -427,24 +427,41 @@ func buildMongoCondition(cond types.Condition) bson.D {
 }
 
 // buildFilter generates a BSON document for MongoDB
-func buildFilter(stream types.StreamInterface) (bson.D, error) {
+func (m *Mongo) buildFilter(stream types.StreamInterface) (bson.D, error) {
+	primaryCursor, secondaryCursor := stream.Cursor()
+	maxPrimaryCursorValue := m.state.GetCursor(stream.Self(), primaryCursor)
+	maxSecondaryCursorValue := m.state.GetCursor(stream.Self(), secondaryCursor)
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: add comments here

File: drivers/mongodb/internal/backfill.go [hunk 15]
```diff
@@ -427,24 +427,41 @@ func buildMongoCondition(cond types.Condition) bson.D {
...
-
-	switch {
-	case len(filter.Conditions) == 0:
+	if len(conditions) == 0 {
 		return bson.D{}, nil
-	case len(filter.Conditions) == 1:
-		return buildMongoCondition(filter.Conditions[0]), nil
-	default:
-		return bson.D{{Key: "$" + filter.LogicalOperator, Value: bson.A{buildMongoCondition(filter.Conditions[0]), buildMongoCondition(filter.Conditions[1])}}}, nil
 	}
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: use switch case

File: drivers/mongodb/internal/backfill.go [hunk 16]
```diff
@@ -472,6 +489,57 @@ func isObjectID(ctx context.Context, collection *mongo.Collection) (bool, error)
...
+			logger.Warnf("max secondary cursor value is nil for stream: %s", stream.ID())
+		}
+		return result.MaxPrimaryCursor, result.MaxSecondaryCursor, nil
+	}
+
+	if err := cursor.Err(); err != nil {
+		return nil, nil, fmt.Errorf("cursor error: %s", err)
+	}
+	logger.Warnf("No documents found for stream: %s", stream.ID())
+	return nil, nil, cursor.Err()
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: warning you can add in abstract
```suggestion
	return nil, nil, cursor.Err()
```

File: pkg/jdbc/jdbc.go (hunk 13 above)
Comment (hash-data) [reply pkg/jdbc/jdbc.go:24]: can you add a comment there

File: pkg/jdbc/jdbc.go [hunk 17]
```diff
@@ -617,12 +615,97 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+	}
+	if maxPrimaryCursorValue == nil {
+		logger.Warnf("max primary cursor value is nil for stream: %s", stream.ID())
+	}
+	return bytesConverter(maxPrimaryCursorValue), maxSecondaryCursorValue, nil
+}
+
+// FilterUpdater is used to update the filter for initial run of incremental sync during backfill.
+// This is to avoid dupliction of records, as cursor value is fetched before the chunk creation.
+func FilterUpdater(opts IncrementalConditionOptions, filter string) (string, []any, error) {
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]:
```suggestion
func ThresholdFilter(opts IncrementalConditionOptions, filter string) (string, []any, error) {
```

File: pkg/jdbc/jdbc.go [hunk 18]
```diff
@@ -617,12 +615,97 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+	if opts.Stream.GetSyncMode() != types.INCREMENTAL {
+		return filter, nil, nil
+	}
+	primaryCursor, secondaryCursor := opts.Stream.Cursor()
+	primaryCursorValue := opts.State.GetCursor(opts.Stream.Self(), primaryCursor)
+	placeholder := GetPlaceholder(opts.Driver)
+
+	conditionMaker := func(opts IncrementalConditionOptions, argumentPosition int, cursorField string, cursorValue any) (string, any, error) {
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]:
```suggestion
	createCondition := func(opts IncrementalConditionOptions, argumentPosition int, cursorField string, cursorValue any) (string, any, error) {
```

File: drivers/mysql/internal/backfill.go [hunk 19]
```diff
@@ -29,6 +29,19 @@ func (m *MySQL) ChunkIterator(ctx context.Context, stream types.StreamInterface,
...
+			Stream: stream,
+			State:  m.state,
+			Client: m.client,
+		}
+
+		filter, args, err := jdbc.FilterUpdater(opts, filter)
+		if err != nil {
+			return fmt.Errorf("failed to update filter limiting the cursor values: %s", err)
+		}
+		logger.Infof("Starting backfill with filter: %s, args: %v", filter, args)
```
Comment (hash-data) [inline drivers/mysql/internal/backfill.go]: let us rename this filter to threshold filter

File: drivers/oracle/internal/backfill.go [hunk 20]
```diff
@@ -135,3 +142,11 @@ func (o *Oracle) GetOrSplitChunks(ctx context.Context, pool *destination.WriterP
 	}
 	return splitViaRowId(stream)
 }
+
+func (o *Oracle) FetchMaxCursorValues(ctx context.Context, stream types.StreamInterface) (any, any, error) {
```
Comment (hash-data) [inline drivers/oracle/internal/backfill.go]: this function should be part of incremental file

File: pkg/jdbc/jdbc.go [hunk 21]
```diff
@@ -453,9 +461,11 @@ func OracleChunkRetrievalQuery(taskName string) string {
 }
 
 // OracleIncrementalValueFormatter is used to format the value of the cursor field for Oracle incremental sync, mainly because of the various timestamp formats
-func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, lastCursorValue any, opts IncrementalConditionOptions) (string, any, error) {
+func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, greaterThan bool, lastCursorValue any, opts IncrementalConditionOptions) (string, any, error) {
 	// Get the datatype of the cursor field from streams
 	stream := opts.Stream
+	// in case of incremental sync, during backfill to avoid duplicate records we need to use <= else use >
+	operator := utils.Ternary(greaterThan, ">", "<=").(string)
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]: let us discuss

File: pkg/jdbc/jdbc.go [hunk 22]
```diff
@@ -617,12 +615,97 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+		maxSecondaryCursorValue = bytesConverter(maxSecondaryCursorValue)
+	} else {
+		err := client.QueryRowContext(ctx, cursorValueQuery).Scan(&maxPrimaryCursorValue)
+		if err != nil {
+			return nil, nil, fmt.Errorf("failed to scan primary cursor value: %s", err)
+		}
+	}
+	if maxPrimaryCursorValue == nil {
+		logger.Warnf("max primary cursor value is nil for stream: %s", stream.ID())
+	}
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]: add a check in abstract about nil

File: pkg/jdbc/jdbc.go [hunk 23]
```diff
@@ -617,12 +615,97 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+		secondaryCursorValue := opts.State.GetCursor(opts.Stream.Self(), secondaryCursor)
+		secondaryCondition, argument, err := conditionMaker(opts, 2, secondaryCursor, secondaryCursorValue)
+		if err != nil {
+			return "", nil, fmt.Errorf("failed to format secondary cursor value: %s", err)
+		}
+		incrementalFilter = fmt.Sprintf("%s AND (%s IS NULL OR %s)", incrementalFilter, QuoteIdentifier(secondaryCursor, opts.Driver), secondaryCondition)
+		arguments = append(arguments, argument)
+	}
+
+	filter = utils.Ternary(filter == "", incrementalFilter, fmt.Sprintf("(%s) AND %s", filter, incrementalFilter)).(string)
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]: let us discuss after you test it

File: pkg/jdbc/jdbc.go [hunk 24]
```diff
@@ -617,12 +615,97 @@ func BuildIncrementalQuery(opts IncrementalConditionOptions) (string, []any, err
...
+
+	conditionMaker := func(opts IncrementalConditionOptions, argumentPosition int, cursorField string, cursorValue any) (string, any, error) {
+		var conditionFilter string
+
+		if opts.Driver == constants.Oracle {
+			return OracleIncrementalValueFormatter(cursorField, placeholder(argumentPosition), false, cursorValue, opts)
+		}
+		conditionFilter = fmt.Sprintf("%s <= %s", QuoteIdentifier(cursorField, opts.Driver), placeholder(argumentPosition))
+		return conditionFilter, cursorValue, nil
+	}
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]: little bit confusing

File: drivers/abstract/backfill.go [hunk 25]
```diff
@@ -18,6 +18,20 @@ func (a *AbstractDriver) Backfill(ctx context.Context, backfilledStreams chan st
...
+			maxPrimaryCursorValue, maxSecondaryCursorValue, err := a.driver.FetchMaxCursorValues(ctx, stream)
+			if err != nil {
+				return fmt.Errorf("failed to fetch max cursor values: %s", err)
+			}
+			primaryCursor, secondaryCursor := stream.Cursor()
+
+			a.state.SetCursor(stream.Self(), primaryCursor, a.reformatCursorValue(maxPrimaryCursorValue))
+			if secondaryCursor != "" {
+				a.state.SetCursor(stream.Self(), secondaryCursor, a.reformatCursorValue(maxSecondaryCursorValue))
+			}
```
Comment (hash-data) [inline drivers/abstract/backfill.go]: you can call this in incremental only

File: drivers/oracle/internal/backfill.go (hunk 20 above)
Comment (vaibhav-datazip) [reply drivers/oracle/internal/backfill.go]: But this function is only used during backfill to fetch the max cursor value.

File: pkg/jdbc/jdbc.go (hunk 22 above)
Comment (vaibhav-datazip) [reply pkg/jdbc/jdbc.go]: need to discuss about secondary cursor as well

File: drivers/mongodb/internal/backfill.go [hunk 26]
```diff
@@ -427,24 +427,46 @@ func buildMongoCondition(cond types.Condition) bson.D {
...
+	case len(filter.Conditions) == 0 && len(conditions) == 0:
 		return bson.D{}, nil
 	case len(filter.Conditions) == 1:
-		return buildMongoCondition(filter.Conditions[0]), nil
+		conditions = append(conditions, buildMongoCondition(filter.Conditions[0]))
+	case len(filter.Conditions) == 2:
+		conditions = append(conditions, bson.D{{Key: "$" + filter.LogicalOperator, Value: bson.A{buildMongoCondition(filter.Conditions[0]), buildMongoCondition(filter.Conditions[1])}}})
 	default:
-		return bson.D{{Key: "$" + filter.LogicalOperator, Value: bson.A{buildMongoCondition(filter.Conditions[0]), buildMongoCondition(filter.Conditions[1])}}}, nil
+		logger.Warnf("multiple conditions are not supported in filter")
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: it should fail will error right?

File: drivers/mongodb/internal/backfill.go [hunk 27]
```diff
@@ -427,24 +427,46 @@ func buildMongoCondition(cond types.Condition) bson.D {
...
+				{Key: primaryCursor, Value: bson.D{{Key: "$lte", Value: maxPrimaryCursorValue}}},
+			})
+		}
+
+		if maxSecondaryCursorValue != nil && secondaryCursor != "" {
+			conditions = append(conditions, bson.D{
+				{Key: secondaryCursor, Value: bson.D{{Key: "$lte", Value: maxSecondaryCursorValue}}},
+			})
+		}
+	}
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: let us create a different function named threshold filter

File: drivers/mysql/internal/backfill.go [hunk 28]
```diff
@@ -29,17 +29,30 @@ func (m *MySQL) ChunkIterator(ctx context.Context, stream types.StreamInterface,
 		pkColumns := stream.GetStream().SourceDefinedPrimaryKey.Array()
 		chunkColumn := stream.Self().StreamMetadata.ChunkColumn
 		sort.Strings(pkColumns)
+
+		opts := jdbc.IncrementalConditionOptions{
```
Comment (hash-data) [inline drivers/mysql/internal/backfill.go]: let us rename this struct to Options

File: drivers/oracle/internal/backfill.go [hunk 29]
```diff
@@ -30,11 +30,25 @@ func (o *Oracle) ChunkIterator(ctx context.Context, stream types.StreamInterface
...
+		State:  o.state,
+		Client: o.client,
+	}
+
+	thresholdFilter, args, err := jdbc.ThresholdFilter(opts, filter)
+	if err != nil {
+		return fmt.Errorf("failed to update filter limiting the cursor values: %s", err)
+	}
+
+	logger.Infof("Starting backfill with filter: %s, args: %v", thresholdFilter, args)
```
Comment (hash-data) [inline drivers/oracle/internal/backfill.go]: let us appen chunk min and max in log

File: pkg/jdbc/jdbc.go [hunk 30]
```diff
@@ -453,9 +461,11 @@ func OracleChunkRetrievalQuery(taskName string) string {
 }
 
 // OracleIncrementalValueFormatter is used to format the value of the cursor field for Oracle incremental sync, mainly because of the various timestamp formats
-func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, lastCursorValue any, opts IncrementalConditionOptions) (string, any, error) {
+func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, isBackfill bool, lastCursorValue any, opts IncrementalConditionOptions) (string, any, error) {
 	// Get the datatype of the cursor field from streams
 	stream := opts.Stream
+	// in case of incremental sync, during backfill to avoid duplicate records we need to use <= else use >
```
Comment (hash-data) [inline pkg/jdbc/jdbc.go]:
```suggestion
	// in case of incremental sync mode, during backfill to avoid duplicate records we need to use '<=', otherwise use '>'
```
