### PR TITLE
Fix: Backoff in mongo chunk splitting

### LINKED ISSUE #128: [Bug] Backoff logic doesn't work on creating chunks from DB
## Environment

- **Deploy method**: built from sources
- **Olake version**: 0.0.5
- **OS**: `Mac OS`
- **Cloud Provider**: Azure VM
- **Docker Params (if deployed with docker)**:  Normal ones

## Description
Currently sometime db might fail or give error while calculating the chunks. Ideally the backoff should be applicable on that as its applicable on normal data fetch queries.

## Steps to reproduce

restart db when Mongodb splitvector command is running

## Expected behavior

It should have retried splitVector query as per mentioned backoff

## Actual behavior

{"level":"info","message":"Starting ChangeStream process in driver","time":"2025-03-06T19:54:26Z"}
{"level":"info","message":{"type":"STATE","state":{"type":"STREAM","streams":[{"stream":"tweets","namespace":"twitter_data","sync_mode":"","state":{"_data":"8267C9FD72000000022B0429296E1404"}}]}},"time":"2025-03-06T19:54:26Z"}
{"level":"info","time":"2025-03-06T19:54:26Z","message":"Starting full load for stream [twitter_data.tweets]"}
{"level":"info","time":"2025-03-06T19:54:26Z","message":"Total expected count for stream twitter_data.tweets: 232604508"}
{"level":"fatal","time":"2025-03-06T19:56:29Z","message":"error occurred while reading records: failed to get chunk boundaries: splitVector failed: connection(4.187.151.102:27017[-10]) socket was unexpectedly closed: EOF"}

### PR DESCRIPTION
**Pull request by debarshee2004**
# Description

Fixes #128 

This PR adds retry logic to the `splitChunks` method when using the default splitVector strategy. Previously, if MongoDB went down or encountered a connection issue during the `splitVector` command, the operation would fail immediately without retrying, despite having a configured retry count in the config.

Now, the `splitVector` command will utilize the `RetryOnBackoff` functionality correctly, allowing the system to handle temporary database failures gracefully by retrying the operation according to the configured backoff parameters.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Verified the fix compiles successfully and resolves the reported type error
- [x] Tested by restarting MongoDB during chunk calculation to verify the retry mechanism works
- [x] Confirmed that retry count from configuration is respected

# Screenshots or Recordings

N/A

## Related PR's (If Any):
None

### CODE REVIEW

File: drivers/mongodb/internal/backfill.go [hunk 1]
```diff
@@ -215,9 +215,16 @@ func (m *Mongo) splitChunks(ctx context.Context, collection *mongo.Collection, s
 	case "timestamp":
 		return timestampStrategy()
 	default:
-		return splitVectorStrategy()
+		var chunks []types.Chunk
+		err := base.RetryOnBackoff(m.config.RetryCount, 1*time.Second, func() error {
```
Comment (shubham19may) [inline drivers/mongodb/internal/backfill.go]: @debarshee2004 make it a minute.

Comment (shubham19may) [reply drivers/mongodb/internal/backfill.go:219]: @debarshee2004 have you tested this?

File: drivers/mongodb/internal/backfill.go [hunk 2]
```diff
@@ -215,9 +215,16 @@ func (m *Mongo) splitChunks(ctx context.Context, collection *mongo.Collection, s
...
+			var err error
+			chunks, err = splitVectorStrategy()
+			return err
```
Comment (shubham19may) [inline drivers/mongodb/internal/backfill.go]: add proper logging on how many retry attempts. Kindly check the other code properly.

File: drivers/mongodb/internal/backfill.go [hunk 3]
```diff
@@ -215,9 +215,16 @@ func (m *Mongo) splitChunks(ctx context.Context, collection *mongo.Collection, s
 	case "timestamp":
 		return timestampStrategy()
 	default:
-		return splitVectorStrategy()
+		var chunks []types.Chunk
+		err := base.RetryOnBackoff(m.config.RetryCount, 1*time.Second, func() error {
+			var err error
+			chunks, err = splitVectorStrategy()
```
Comment (shubham19may) [inline drivers/mongodb/internal/backfill.go]: rename error var as it might shadow upper error var.

File: drivers/mongodb/internal/backfill.go [hunk 4]
```diff
@@ -215,9 +215,16 @@ func (m *Mongo) splitChunks(ctx context.Context, collection *mongo.Collection, s
 	case "timestamp":
 		return timestampStrategy()
```
Comment (shubham19may) [inline drivers/mongodb/internal/backfill.go]: This should also come under retry. This also has queries to fetch extreme.

**Comment by dinocodesx** [comment]
Hey @shubham19may , I am updating the code and letting you know.

**Comment by dinocodesx** [comment]
This is the code I decided to go with because:
- Uses a single strategy function variable and strategy name to avoid duplicating code
- Uses a single retryCounter and set of log messages
- Maintains the functionality while being more concise and DRY

```go
	var strategyFunc func() ([]types.Chunk, error)
	var strategyName string

	switch m.config.PartitionStrategy {
	case "timestamp":
		strategyFunc = timestampStrategy
		strategyName = "Timestamp"
	default:
		strategyFunc = splitVectorStrategy
		strategyName = "Split Vector"
	}

	var chunks []types.Chunk
	var retryCounter int

	err := base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
		var retryErr error
		chunks, retryErr = strategyFunc()

		if retryErr != nil {
			retryCounter++
			logger.Infof("Number of Retry of %s Strategy %d", strategyName, retryCounter)
		}

		return retryErr
	})

	if retryCounter > 0 {
		logger.Infof("%s Strategy completed after %d retries", strategyName, retryCounter)
	}

	return chunks, err
```

do correct me if I am wrong or need any further changes.

File: drivers/mongodb/internal/backfill.go [hunk 5]
```diff
@@ -211,13 +211,40 @@ func (m *Mongo) splitChunks(ctx context.Context, collection *mongo.Collection, s
...
+	if retryCounter > 0 {
+		logger.Infof("%s Strategy completed after %d retries", strategyName, retryCounter)
+	}
+
+	return chunks, err
 }
+
 func (m *Mongo) totalCountInCollection(ctx context.Context, collection *mongo.Collection) (int64, error) {
 	var countResult bson.M
 	command := bson.D{{
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: instead of retry here can we not add backoff on calling function ?

Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: Yes we can do that. I believe this is a better form of implementation. 

```go
func (m *Mongo) splitChunks(ctx context.Context, collection *mongo.Collection, stream protocol.Stream) ([]types.Chunk, error) {
	splitVectorStrategy := func() ([]types.Chunk, error) {
		var chunks []types.Chunk
		// Backoff on function call
		strategyErr := base.RetryOnBackoff(3, 1*time.Minute, func() error {
			getChunkBoundaries := func() ([]*primitive.ObjectID, error) {
				getID := func(order int) (primitive.ObjectID, error) {
					var doc bson.M
					err := collection.FindOne(ctx, bson.D{}, options.FindOne().SetSort(bson.D{{Key: "_id", Value: order}})).Decode(&doc)
					if err == mongo.ErrNoDocuments {
						return primitive.NilObjectID, nil
					}
					return doc["_id"].(primitive.ObjectID), err
				}
				...
```

This is my though. should I proceed with this?

Comment (hash-data) [reply drivers/mongodb/internal/backfill.go]: you can pass the function: m.splitChunks to utils.backoff
and  handle err only as we are printing err properly in backoff 
action to be taken on below code:
```

		// Generate and update chunks
		chunksArray, err = m.splitChunks(backfillCtx, collection, stream)
		if err != nil {
			return err
		}

```

Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: > you can pass the function: m.splitChunks to utils.backoff and handle err only as we are printing err properly in backoff action to be taken on below code:
> 
> ```
> 
> 		// Generate and update chunks
> 		chunksArray, err = m.splitChunks(backfillCtx, collection, stream)
> 		if err != nil {
> 			return err
> 		}
> ```

I am really sorry but I did not understand what you meant, can you please elaborate. As in the backfill function `m.splitChunks` is being called, do you want me to handle the backoff on that function call? Like this:

```go
err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
            var retryErr error
            chunksArray, retryErr = m.splitChunks(backfillCtx, collection, stream)
            return retryErr
        })
        if err != nil {
            return err
        }
```

(I am really sorry for wasting so much of your time.)

**Comment by dinocodesx** [comment]
Please do note that the commits are due to merging the recent change in the master branch of this repository and does not have any code change.

File: drivers/mongodb/internal/backfill.go (hunk 5 above)
Comment (hash-data) [reply drivers/mongodb/internal/backfill.go]: chunksArray can be passed via reference, so that you just need to add this line:
```
err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute,m.splitChunks(backfillCtx, collection, stream, chunksArray))
  if err != nil {
      return err
  }
```

File: drivers/mongodb/internal/backfill.go [hunk 6]
```diff
@@ -43,7 +43,11 @@ func (m *Mongo) backfill(stream protocol.Stream, pool *protocol.WriterPool) erro
 		pool.AddRecordsToSync(recordCount)
 
 		// Generate and update chunks
-		chunksArray, err = m.splitChunks(backfillCtx, collection, stream)
+		err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
+			var retryErr error
+			chunksArray, retryErr = m.splitChunks(backfillCtx, collection, stream)
+			return retryErr
+		})
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: can you pass the chunks array as reference to m.SplitChunks to make code look clean.

Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: Okay sure I am updating it, and also adding proper logging for backoff.

File: drivers/mongodb/internal/backfill.go (hunk 5 above)
Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: The code you recommended is giving an error as `m.SplitChunks` returns two types a `[]types.Chunk` and an `error`, and for the fact that `m.SplitChunk` cannot accept a chunkArray as a parameter.

> ```go
> err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute,m.splitChunks(backfillCtx, collection, stream, chunksArray))
>   if err != nil {
>     return err
>  }
> ```

image

Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: Add I have added logs as requested by @shubham19may Da previously 

```go
// Generate and update chunks
		var retryCount int
		var retryErr error
		err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
			retryCount++
			chunksArray, retryErr = m.splitChunks(backfillCtx, collection, stream)
			return retryErr
		})
		if err != nil {
			logger.Errorf("Failed to split chunks after %d attempts", retryCount)
			return err
		}
		logger.Infof("Successfully split chunks after %d attempts", retryCount)
```

File: drivers/mongodb/internal/backfill.go [hunk 7]
```diff
@@ -43,7 +43,11 @@ func (m *Mongo) backfill(stream protocol.Stream, pool *protocol.WriterPool) erro
 		pool.AddRecordsToSync(recordCount)
 
 		// Generate and update chunks
-		chunksArray, err = m.splitChunks(backfillCtx, collection, stream)
+		err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
+			var retryErr error
+			chunksArray, retryErr = m.splitChunks(backfillCtx, collection, stream)
```
Comment (shubham19may) [inline drivers/mongodb/internal/backfill.go:48]: Why are we not logging the retryErr?

Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go:48]: I have added the code after noticing that I have forgotten and I am also updating the PR. 

```go
// Generate and update chunks
		var retryCount int
		var retryErr error
		err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
			retryCount++
			chunksArray, retryErr = m.splitChunks(backfillCtx, collection, stream)
			return retryErr
		})
		if err != nil {
			logger.Errorf("Failed to split chunks after %d attempts", retryCount)
			return err
		}
		logger.Infof("Successfully split chunks after %d attempts", retryCount)
```

**Comment by dinocodesx** [comment]
@shubham19may @hash-data are any further changes required or can we move forward with this PR.

**Review by shubham19may — DISMISSED** [review]

File: drivers/mongodb/internal/backfill.go (hunk 5 above)
Comment (hash-data) [reply drivers/mongodb/internal/backfill.go]: you may need to add it m.splits arguments as well to accept chunksArray

**Comment by hash-data** [comment]
Hi @debarshee2004 can you ack my comment on passing chunksArray reference.

File: drivers/mongodb/internal/backfill.go [hunk 8]
```diff
@@ -43,10 +43,18 @@ func (m *Mongo) backfill(stream protocol.Stream, pool *protocol.WriterPool) erro
 		pool.AddRecordsToSync(recordCount)
 
 		// Generate and update chunks
-		chunksArray, err = m.splitChunks(backfillCtx, collection, stream)
+		var retryCount int
+		var retryErr error
+		err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute, func() error {
+			retryCount++
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: not required

File: drivers/mongodb/internal/backfill.go [hunk 9]
```diff
@@ -43,10 +43,18 @@ func (m *Mongo) backfill(stream protocol.Stream, pool *protocol.WriterPool) erro
...
+			chunksArray, retryErr = m.splitChunks(backfillCtx, collection, stream)
+			return retryErr
+		})
 		if err != nil {
+			logger.Errorf("Failed to split chunks after %d attempts", retryCount)
```
Comment (hash-data) [inline drivers/mongodb/internal/backfill.go]: logging already happening in retry func, so it also not required.

File: drivers/mongodb/internal/backfill.go (hunk 8 above)
Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: Okay 👍

File: drivers/mongodb/internal/backfill.go (hunk 9 above)
Comment (dinocodesx) [reply drivers/mongodb/internal/backfill.go]: Okay then I am removing this loggings 👍

**Comment by dinocodesx** [comment]
> Hi @debarshee2004 can you ack my comment on passing chunksArray reference.

Hi @hash-data, I actually directly used the code which you provided but it had some issues:

The code you recommended is giving an error as `m.SplitChunks` returns two types a `[]types.Chunk` and an `error`, and for the fact that `m.SplitChunk` cannot accept a chunkArray as a parameter.

> ```go
> err = base.RetryOnBackoff(m.config.RetryCount, 1*time.Minute,m.splitChunks(backfillCtx, collection, stream, chunksArray))
>   if err != nil {
>     return err
>  }
> ```

image

So  I wanted to know should I create a separate Retry Function which can handle that argument? Or any thing else.

**Comment by dinocodesx** [comment]
Hi @hash-data , can you please notify if there is any further change required if not I will just update this branch by removing the loggings.

**Comment by dinocodesx** [comment]
@shubham19may I have updated the code by removing the logging as requested. Can you check it.

**Comment by shubham19may** [comment]
> @shubham19may I have updated the code by removing the logging as requested. Can you check it.

@debarshee2004 what Ankit meant was, make changes to chunksArr function to accept the array (pointer) as a one more variable and just populate it in that function itself so this code can be reduced to just 1 line. 

Do let me know if there are any other doubts.

**Comment by dinocodesx** [comment]
> > @shubham19may I have updated the code by removing the logging as requested. Can you check it.
> 
> @debarshee2004 what Ankit meant was, make changes to chunksArr function to accept the array (pointer) as a one more variable and just populate it in that function itself so this code can be reduced to just 1 line. 
> 
> Do let me know if there are any other doubts.

Okay, now I understand 😅. Sorry for the trouble, I am updating the code and letting you know. @shubham19may

**Comment by dinocodesx** [comment]
@shubham19may @hash-data  `m.splitChunks` returns two values and the retry function only cares about the error. So how do you want to proceed with that? (Again I am really sorry for disturbing you guys so much.)

**Comment by hash-data** [comment]
> @shubham19may @hash-data `m.splitChunks` returns two values and the retry function only cares about the error. So how do you want to proceed with that? (Again I am really sorry for disturbing you guys so much.)

if chunks array is passed as reference then you only get one return value which is error.

**Comment by dinocodesx** [comment]
> if chunks array is passed as reference then you only get one return value which is error.

Now that I am sending that as an reference it solve one error but one remains: 
`multiple-value m.splitChunks(backfillCtx, collection, stream, &chunksArray) (value of type ([]types.Chunk, error)) in single-value context`

image

I tried some other syntaxes all were give same error. @hash-data

**Comment by shubham19may** [comment]
> > if chunks array is passed as reference then you only get one return value which is error.
> 
> Now that I am sending that as an reference it solve one error but one remains: `multiple-value m.splitChunks(backfillCtx, collection, stream, &chunksArray) (value of type ([]types.Chunk, error)) in single-value context`
> 
> image
> 
> I tried some other syntaxes all were give same error. @hash-data

@debarshee2004 please make sure you have gone through a basics of golang (May be a udemy tutorial or something else) We won't be able to help you on these smaller issues on coding syntax not being working as we have many PRs to be reviewed and merged. You will have to figure this on your own.

**Comment by dinocodesx** [comment]
Unfortunately, that seems to be the case 😅, as I just started with go last month, but I will figure the problem and fix the issue. Sorry.

**Review by shubham19may — APPROVED** [review]

**Review by shubham19may — APPROVED** [review]
