### PR TITLE
fix: fixed signedness bitmap

### LINKED ISSUE #842: Incorrect data type mapping for MySQL for INT UNSGINED
## Description
Now MySQL INT UNSIGNED is mapped to int type. Its causing overflowing for value that are bigger than 2147483647 (max for INT).
In MySQL value 3349714808 is saved in Parquet as -945252488.

## Expected behavior
INT UNSGINED type should be mapped to bigint to properly save large values.

### PR DESCRIPTION
**Pull request by saksham-datazip**
# Description

This PR fixes an issue in the handling of the signedness bitmap for MySQL numeric columns.

Previously, the implementation relied on the UnsignedMap function from the MySQL driver to determine whether numeric columns were signed or unsigned. However, the driver's internal isNumeric logic had a mismatch with MySQL server behavior.

Specifically, the driver’s isNumeric function did not include the YEAR column type as a numeric type, while the MySQL server does include YEAR when generating the signedness bitmap in the binlog TABLE_MAP_EVENT.

Because of this mismatch:

MySQL writes a signedness bit for the YEAR column.

The driver skips YEAR when iterating numeric columns.

This causes a bit offset in the signedness bitmap parsing.

As a result, all numeric columns appearing after a YEAR column may be interpreted with incorrect signedness, which can lead to incorrect values being decoded during CDC processing.

This issue was introduced when switching to the UnsignedMap function from the MySQL driver in the following PR:

https://github.com/datazip-inc/olake/pull/846

This PR resolves the issue by aligning the numeric type handling with MySQL server behavior and ensuring that YEAR is treated consistently when parsing the signedness bitmap.

Relevant MySQL source references for signedness metadata:

https://github.com/mysql/mysql-server/blob/trunk/sql/field_common_properties.h#L11238

https://github.com/mysql/mysql-server/blob/trunk/sql/field_common_properties.h#L204

These references show how MySQL determines whether a column type contains signedness information when generating binlog metadata.

Fixes #842

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

The fix was validated using CDC pipelines with both Iceberg and Parquet destinations.

A table containing a YEAR column followed by numeric columns was created. CDC replication was executed and the decoded values were verified to ensure that unsigned numeric columns appearing after the YEAR column are interpreted correctly.

Test procedure:

Create a table with a YEAR column and numeric columns following it.

Insert values into unsigned numeric columns.

Run CDC replication.

Verify decoded values in the destination.

- [x] Scenario A — CDC replication to Iceberg destination
- [x] Scenario B — CDC replication to Parquet destination

# Screenshots or Recordings
Output in iceberg:-
image

Output in parquet :-
image

## Documentation
- [x] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [x] N/A (bug fix, refactor, or test changes only)

## Related PR's (If Any):
https://github.com/datazip-inc/olake/pull/846

### CODE REVIEW

File: pkg/binlog/filter.go [hunk 1]
```diff
@@ -59,10 +59,10 @@ func (f ChangeFilter) FilterRowsEvent(ctx context.Context, e *replication.RowsEv
 		return nil
 	}
 
-	unsignedMap := e.Table.UnsignedMap()
+	unsignedMap := UnsignedMap(e.Table)
 	columnTypes := make([]string, len(e.Table.ColumnType))
 	for i, ct := range e.Table.ColumnType {
-		columnTypes[i] = mysqlTypeName(ct, unsignedMap != nil && unsignedMap[i])
+		columnTypes[i] = mysqlTypeName(ct, unsignedMap[i])
```
Comment (saksham-datazip) [inline pkg/binlog/filter.go]: add unsignedMap != nil this as well

File: pkg/binlog/filter.go [hunk 2]
```diff
@@ -215,3 +215,45 @@ func mysqlTypeName(t byte, unsigned bool) string {
...
+// Note that only columns with signedness information will be returned.
+// nil is returned if not available or no signedness columns at all.
+func UnsignedMap(tableMap *replication.TableMapEvent) map[int]bool {
+	if len(tableMap.SignednessBitmap) == 0 {
+		return nil
+	}
+	ret := make(map[int]bool)
+	i := 0
+	for _, field := range tableMap.SignednessBitmap {
+		for c := byte(0x80); c != 0; {
```
Comment (saksham-datazip) [inline pkg/binlog/filter.go]: use 0x80 similar to driver code

File: pkg/binlog/filter.go [hunk 3]
```diff
@@ -215,3 +215,45 @@ func mysqlTypeName(t byte, unsigned bool) string {
...
+			if IsNumericColumn(i, tableMap) {
+				ret[i] = field&byte(c) != 0
+				c >>= 1
+			}
+			i++
+			if i >= len(tableMap.ColumnType) {
+				break
```
Comment (saksham-datazip) [inline pkg/binlog/filter.go]: use return ret similar to mysql-driver

File: pkg/binlog/filter.go [hunk 4]
```diff
@@ -215,3 +215,45 @@ func mysqlTypeName(t byte, unsigned bool) string {
...
+	ret := make(map[int]bool)
+	i := 0
+	for _, field := range tableMap.SignednessBitmap {
+		for c := byte(0x80); c != 0; {
+			if IsNumericColumn(i, tableMap) {
+				ret[i] = field&byte(c) != 0
+				c >>= 1
+			}
+			i++
+			if i >= len(tableMap.ColumnType) {
```
Comment (saksham-datazip) [inline pkg/binlog/filter.go]: change len(tableMap.ColumnType) to int(tableMap.ColumnCount)
similar to mysql-drivers code

Comment (saksham-datazip) [reply pkg/binlog/filter.go]: image

File: pkg/binlog/filter.go (hunk 1 above)
Comment (saksham-datazip) [reply pkg/binlog/filter.go]: solved

File: pkg/binlog/filter.go (hunk 2 above)
Comment (saksham-datazip) [reply pkg/binlog/filter.go]: solved

File: pkg/binlog/filter.go (hunk 3 above)
Comment (saksham-datazip) [reply pkg/binlog/filter.go]: solved

File: pkg/binlog/filter.go [hunk 5]
```diff
@@ -215,3 +215,45 @@ func mysqlTypeName(t byte, unsigned bool) string {
 		return fmt.Sprintf("UNKNOWN_TYPE: %d", t)
 	}
 }
+
+// UnsignedMap returns a map: column index -> unsigned.
+// Note that only columns with signedness information will be returned.
+// nil is returned if not available or no signedness columns at all.
+func UnsignedMap(tableMap *replication.TableMapEvent) map[int]bool {
```
Comment (vikaxsh) [inline pkg/binlog/filter.go]: Make TableMapEvent the receiver for UnsignedMap and IsNumericColumn

Comment (vikaxsh) [reply pkg/binlog/filter.go]: since these are from external library, can't extend directly
rename these to unsignedMap and isNumericColumn

File: pkg/binlog/filter.go [hunk 6]
```diff
@@ -215,3 +215,45 @@ func mysqlTypeName(t byte, unsigned bool) string {
...
+	ret := make(map[int]bool)
+	i := 0
+	for _, field := range tableMap.SignednessBitmap {
+		for c := 0x80; c != 0; {
+			if IsNumericColumn(i, tableMap) {
+				ret[i] = field&byte(c) != 0
+				c >>= 1
+			}
+			i++
+			if i >= len(tableMap.ColumnType) {
```
Comment (vikaxsh) [inline pkg/binlog/filter.go]: Once verified that this is an equivalent substitute, it shouldn’t introduce any breaking changes.

Comment (saksham-datazip) [reply pkg/binlog/filter.go]: here columnCount and columnType are defined and used and clearly columnType is defined as biteslice exactly of length columnCount
Line number :- 118 to 123 
https://github.dev/go-mysql-org/go-mysql/replication/row_event.go

File: pkg/binlog/filter.go (hunk 5 above)
Comment (saksham-datazip) [reply pkg/binlog/filter.go]: changed

**Review by vikaxsh — APPROVED** [review]
