### PR TITLE
fix: add context while querying (sql/sqlx) (#319)

### LINKED ISSUE #319: use ctx while querying
https://github.com/datazip-inc/olake/blob/5284238d57b8dfd3b61adbe6b4795650ec558980/drivers/postgres/internal/backfill.go#L44-L49

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in 5284238d57b8dfd3b61adbe6b4795650ec558980. It&#x27;s been assigned to @hash-data because they committed the code.

### PR DESCRIPTION
**Pull request by ashh1215**
# Description

Added context parameter to all database query methods in driver files.

Fixes #319

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] `go build` passes for all modified drivers
- [x]  `go vet` passes with no errors
- [ ] Integration tests (attempted locally but encountered Docker connectivity issues - will rely on CI)

## Documentation

- [ ] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [x] N/A (bug fix, refactor, or test changes only)

### CODE REVIEW

File: drivers/postgres/internal/cdc.go [hunk 1]
```diff
@@ -100,9 +100,11 @@ func (p *Postgres) PostCDC(ctx context.Context, _ types.StreamInterface, noErr b
 	return nil
 }
 
-func doesReplicationSlotExists(conn *sqlx.DB, slotName string, publication string) (bool, error) {
+
```
Comment (vaibhav-datazip) [inline drivers/postgres/internal/cdc.go]: Remove unnecessary blank lines which were added. This is one of them

File: drivers/postgres/internal/postgres.go [hunk 2]
```diff
@@ -113,9 +113,11 @@ func (p *Postgres) Setup(ctx context.Context) error {
 			return fmt.Errorf("the CDC initial wait time must be at least 120 seconds and less than 2400 seconds")
 		}
 
+
 		logger.Infof("CDC initial wait time set to: %d", cdc.InitialWaitTime)
 
-		exists, err := doesReplicationSlotExists(pgClient, cdc.ReplicationSlot, cdc.Publication)
+		exists, err := doesReplicationSlotExists(ctx, pgClient, cdc.ReplicationSlot, cdc.Publication)
```
Comment (vaibhav-datazip) [inline drivers/postgres/internal/postgres.go:118]: Still there many queries which are being fired with ctx here are which I have found. 

- [x] jdbc.go
  - [x] OracleIncrementalValueFormatter function
    ```
    query := fmt.Sprintf("SELECT DATA_TYPE FROM ALL_TAB_COLUMNS WHERE OWNER = '%s' AND TABLE_NAME = '%s' AND COLUMN_NAME = '%s'", stream.Namespace(), stream.Name(), cursorField)
    	err = opts.Client.QueryRowContext(ctx, query).Scan(&datatype)
    ```
  - [x] MySQLVersion function

    ```
    func MySQLVersion(client *sqlx.DB) (int, int, error) {
    	var version string
    	err := client.QueryRow("SELECT @@version").Scan(&version)
    ```
- [x] pgoutput.go
  - [x]  StreamChanges function -> can be changed to get context
    ```
    if err := db.Get(&slot, fmt.Sprintf(ReplicationSlotTempl, p.socket.ReplicationSlot)); err != nil {
    ```
- [x] replicator.go
  - [x] NewReplicator function
    ```
    if err := db.Get(&slot, fmt.Sprintf(ReplicationSlotTempl, config.ReplicationSlotName)); err != nil {
    ```
- [x] waljs.go
  - [x]  StreamChanges function
    ```
    if err := db.Get(&slot, fmt.Sprintf(ReplicationSlotTempl, w.socket.ReplicationSlot)); err != nil {
    ```
- [x] binlog.go
  - [x] GetCurrentBinlogPosition 
    ```
    rows, err := client.Query(query)
    	if err != nil {
    		return mysql.Position{}, fmt.Errorf("failed to get master status: %s", err)
    	}
    ```
- [x] postgres.go
  - [x] GetStreamsNames function
    ```
    	var tableNamesOutput []Table
    	err := p.client.Select(&tableNamesOutput, getPrivilegedTablesTmpl)
    	if err != nil {
    ```
  - [x] ProduceSchema function : columnSchemaOutput
    ```
    var columnSchemaOutput []ColumnDetails
    		err := p.client.Select(&columnSchemaOutput, getTableSchemaTmpl, schemaName, streamName)
    		if err != nil {
    ```
  - [x] ProduceSchema function : primaryKeyOutput
    ```
    var primaryKeyOutput []ColumnDetails
    		err = p.client.SelectContext(ctx, &primaryKeyOutput, getTablePrimaryKey, schemaName, streamName)
    		if err != nil {
    ```
- [x] postgres cdc.go
  - [x] validateReplicationSlot function
    ```
    slot := waljs.ReplicationSlot{}
    	err := conn.Get(&slot, fmt.Sprintf(waljs.ReplicationSlotTempl, slotName))
    	if err != nil {
    ``` 
- [x] postgres backfill.go
  - [x] ChunkIterator function
    ```
    return tx.Query(query, args...)
    ```

Comment (vaibhav-datazip) [reply drivers/postgres/internal/postgres.go:118]: You can check if there are more places where context needs to be passed

**Comment by vaibhav-datazip** [comment]
There is still a function in `jdbc.go`
inside the OracleIncrementalValueFormatter function , currently we are using 
```
err = opts.Client.QueryRowContext(context.Background(), query).Scan(&datatype)
```

instead pass a ctx to the function and use that here.

Also you can run the sync for the drivers which you have modified, as test if all the functionalities are working fine.

**Comment by vaibhav-datazip** [comment]
LGTM

File: drivers/mysql/internal/incremental.go [hunk 3]
```diff
@@ -18,10 +18,12 @@ func (m *MySQL) StreamIncrementalChanges(ctx context.Context, stream types.Strea
...
-		Driver: constants.MySQL,
-		Stream: stream,
-		State:  m.state,
-		Filter: filter,
+		Context: ctx,
+		Driver:  constants.MySQL,
+		Stream:  stream,
+		State:   m.state,
+		Client:  m.client,
+		Filter:  filter,
```
Comment (vishalm0509) [inline drivers/mysql/internal/incremental.go]: Suggest removing client and context from the struct.

- `context` can be passed to functions as arguments.
- `client` seems to be required only for Oracle, so let's add it only for that.

Comment (ashh1215) [reply drivers/mysql/internal/incremental.go]: Yeah I've fixed it with the new commit. Please take a look. Thanks.

**Comment by vaibhav-datazip** [comment]
Hi @ashh1215 , can you please resolve these conflicts in your PR

File: pkg/jdbc/jdbc.go [hunk 4]
```diff
@@ -461,7 +461,7 @@ func OracleChunkRetrievalQuery(taskName string) string {
 }
 
 // OracleIncrementalValueFormatter is used to format the value of the cursor field for Oracle incremental sync, mainly because of the various timestamp formats
-func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, isBackfill bool, lastCursorValue any, opts DriverOptions) (string, any, error) {
+func OracleIncrementalValueFormatter(ctx context.Context, client *sqlx.DB, cursorField, argumentPlaceholder string, lastCursorValue any, opts IncrementalConditionOptions) (string, any, error) {
```
Comment (vishalm0509) [inline pkg/jdbc/jdbc.go]: `IncrementalConditionOptions` it's missing. Also why this change? can we use DriverOptions only ?

File: pkg/jdbc/jdbc.go [hunk 5]
```diff
@@ -572,11 +572,11 @@ type DriverOptions struct {
 	Driver constants.DriverType
 	Stream types.StreamInterface
 	State  *types.State
-	Client *sqlx.DB
+	Filter string
```
Comment (vishalm0509) [inline pkg/jdbc/jdbc.go]: Why have we added `Filter` here, can we remove it.

File: pkg/jdbc/jdbc.go [hunk 6]
```diff
@@ -572,11 +572,11 @@ type DriverOptions struct {
...
 }
 
 // BuildIncrementalQuery generates the incremental query SQL based on driver type
-func BuildIncrementalQuery(opts DriverOptions) (string, []any, error) {
+func BuildIncrementalQuery(ctx context.Context, client *sqlx.DB, opts IncrementalConditionOptions) (string, []any, error) {
```
Comment (vishalm0509) [inline pkg/jdbc/jdbc.go]: Let's use DriverOptions only.

File: drivers/postgres/internal/incremental.go [hunk 7]
```diff
@@ -16,7 +16,7 @@ func (p *Postgres) StreamIncrementalChanges(ctx context.Context, stream types.St
 		Stream: stream,
 		State:  p.state,
 	}
-	incrementalQuery, queryArgs, err := jdbc.BuildIncrementalQuery(opts)
+	incrementalQuery, queryArgs, err := jdbc.BuildIncrementalQuery(ctx, nil, opts)
```
Comment (vishalm0509) [inline drivers/postgres/internal/incremental.go]: Let's pass client here as well

File: pkg/jdbc/jdbc.go (hunk 4 above)
Comment (vishalm0509) [reply pkg/jdbc/jdbc.go]: `isBackfill` is missing here. Please check again, I think the merge conflicts are not resolved properly.

File: pkg/jdbc/jdbc.go [hunk 8]
```diff
@@ -593,7 +593,7 @@ func BuildIncrementalQuery(opts DriverOptions) (string, []any, error) {
 	// buildCursorCondition creates the SQL condition for incremental queries based on cursor fields.
 	buildCursorCondition := func(cursorField string, lastCursorValue any, argumentPosition int) (string, any, error) {
 		if opts.Driver == constants.Oracle {
-			return OracleIncrementalValueFormatter(cursorField, placeholder(argumentPosition), false, lastCursorValue, opts)
+			return OracleIncrementalValueFormatter(ctx, client, cursorField, placeholder(argumentPosition), lastCursorValue, opts)
```
Comment (vishalm0509) [inline pkg/jdbc/jdbc.go]: Add isBackfill here and please check all other places where it might be required.

File: drivers/oracle/internal/incremental.go [hunk 9]
```diff
@@ -16,9 +16,9 @@ func (o *Oracle) StreamIncrementalChanges(ctx context.Context, stream types.Stre
 		Driver: constants.Oracle,
 		Stream: stream,
 		State:  o.state,
-		Client: o.client,
+		Filter: filter,
```
Comment (vishalm0509) [inline drivers/oracle/internal/incremental.go]: `Filter` is not needed here

File: drivers/oracle/internal/backfill.go [hunk 10]
```diff
@@ -59,9 +59,16 @@ func (o *Oracle) ChunkIterator(ctx context.Context, stream types.StreamInterface
 
 func (o *Oracle) GetOrSplitChunks(ctx context.Context, pool *destination.WriterPool, stream types.StreamInterface) (*types.Set[types.Chunk], error) {
 	splitViaRowId := func(stream types.StreamInterface) (*types.Set[types.Chunk], error) {
+		var currentSCN string
+		query := jdbc.OracleCurrentSCNQuery()
```
Comment (vishalm0509) [inline drivers/oracle/internal/backfill.go]: Please resolve the merge conflicts properly.

Comment (vishalm0509) [reply drivers/oracle/internal/backfill.go]: Can you please check with staging again

File: drivers/mysql/internal/incremental.go [hunk 11]
```diff
@@ -17,7 +17,7 @@ func (m *MySQL) StreamIncrementalChanges(ctx context.Context, stream types.Strea
 		Stream: stream,
 		State:  m.state,
 	}
-	incrementalQuery, queryArgs, err := jdbc.BuildIncrementalQuery(opts)
+	incrementalQuery, queryArgs, err := jdbc.BuildIncrementalQuery(ctx, nil, opts)
```
Comment (vishalm0509) [inline drivers/mysql/internal/incremental.go]: Let's pass `client` here.

Comment (ashh1215) [reply drivers/mysql/internal/incremental.go]: Hello @vishalm0509
Really sorry about the force push, I'll be careful in the future.
I'll look into the issues and try to fix it soon.
Thanks.

File: drivers/oracle/internal/backfill.go [hunk 12]
```diff
@@ -59,9 +59,16 @@ func (o *Oracle) ChunkIterator(ctx context.Context, stream types.StreamInterface
...
+		err := o.client.QueryRowContext(ctx, query).Scan(&currentSCN)
+		if err != nil {
+			return nil, fmt.Errorf("failed to get current SCN: %s", err)
+		}
+
```
Comment (vishalm0509) [inline drivers/oracle/internal/backfill.go]: Can you please check this. The merge conflicts were not resolved properly.

File: drivers/mysql/internal/incremental.go [hunk 13]
```diff
@@ -16,8 +16,9 @@ func (m *MySQL) StreamIncrementalChanges(ctx context.Context, stream types.Strea
 		Driver: constants.MySQL,
 		Stream: stream,
 		State:  m.state,
+		Client: m.client,
```
Comment (vishalm0509) [inline drivers/mysql/internal/incremental.go]: Only Oracle need client to be passed. Can we remove for Other drivers?

File: drivers/postgres/internal/backfill.go [hunk 14]
```diff
@@ -43,8 +42,8 @@ func (p *Postgres) ChunkIterator(ctx context.Context, stream types.StreamInterfa
 	chunkColumn := stream.Self().StreamMetadata.ChunkColumn
 	chunkColumn = utils.Ternary(chunkColumn == "", "ctid", chunkColumn).(string)
 	stmt := jdbc.PostgresChunkScanQuery(stream, chunkColumn, chunk, filter)
-	setter := jdbc.NewReader(ctx, stmt, func(ctx context.Context, query string, queryArgs ...any) (*sql.Rows, error) {
-		return tx.Query(query, args...)
+	setter := jdbc.NewReader(ctx, stmt, func(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
```
Comment (vaibhav-datazip) [inline drivers/postgres/internal/backfill.go]: change this `args` back to `queryArgs` in the function argument , otherwise this will cause error in postgres incremental.

keep it as `args` in return

File: pkg/jdbc/jdbc.go [hunk 15]
```diff
@@ -461,7 +461,7 @@ func OracleChunkRetrievalQuery(taskName string) string {
 }
 
 // OracleIncrementalValueFormatter is used to format the value of the cursor field for Oracle incremental sync, mainly because of the various timestamp formats
-func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, isBackfill bool, lastCursorValue any, opts DriverOptions) (string, any, error) {
+func OracleIncrementalValueFormatter(ctx context.Context, client *sqlx.DB, cursorField, argumentPlaceholder string, isBackfill bool, lastCursorValue any, opts DriverOptions) (string, any, error) {
```
Comment (vaibhav-datazip) [inline pkg/jdbc/jdbc.go]: in oracle we passing client inside opts , so are you passing it here directly in the function ?

File: pkg/jdbc/jdbc.go [hunk 16]
```diff
@@ -479,7 +479,7 @@ func OracleIncrementalValueFormatter(cursorField, argumentPlaceholder string, is
 	}
 
 	query := fmt.Sprintf("SELECT DATA_TYPE FROM ALL_TAB_COLUMNS WHERE OWNER = '%s' AND TABLE_NAME = '%s' AND COLUMN_NAME = '%s'", stream.Namespace(), stream.Name(), cursorField)
-	err = opts.Client.QueryRow(query).Scan(&datatype)
+	err = client.QueryRowContext(ctx, query).Scan(&datatype)
```
Comment (vaibhav-datazip) [inline pkg/jdbc/jdbc.go]: similarly here, you can switch back to opts.client

File: pkg/jdbc/jdbc.go [hunk 17]
```diff
@@ -593,7 +593,7 @@ func BuildIncrementalQuery(opts DriverOptions) (string, []any, error) {
 	// buildCursorCondition creates the SQL condition for incremental queries based on cursor fields.
 	buildCursorCondition := func(cursorField string, lastCursorValue any, argumentPosition int) (string, any, error) {
 		if opts.Driver == constants.Oracle {
-			return OracleIncrementalValueFormatter(cursorField, placeholder(argumentPosition), false, lastCursorValue, opts)
+			return OracleIncrementalValueFormatter(ctx, opts.Client, cursorField, placeholder(argumentPosition), false, lastCursorValue, opts)
```
Comment (vaibhav-datazip) [inline pkg/jdbc/jdbc.go]: remove opts.client from here as well

File: pkg/jdbc/jdbc.go [hunk 18]
```diff
@@ -676,7 +676,7 @@ func ThresholdFilter(opts DriverOptions) (string, []any, error) {
 
 	createThresholdCondition := func(argumentPosition int, cursorField string, cursorValue any) (string, any, error) {
 		if opts.Driver == constants.Oracle {
-			return OracleIncrementalValueFormatter(cursorField, placeholder(argumentPosition), true, cursorValue, opts)
+			return OracleIncrementalValueFormatter(ctx, opts.Client, cursorField, placeholder(argumentPosition), true, cursorValue, opts)
```
Comment (vaibhav-datazip) [inline pkg/jdbc/jdbc.go]: here also , opts.client won't be needed
