### PR TITLE
fix: sync invalid ENUM values as empty string

### LINKED ISSUE #876: Empty ENUM fields are not handled properly in MySQL CDC
## Description
MySQL allows to have empty string in ENUM columns even if empty string was not in the list of possible values.
From MySQL doc
 https://dev.mysql.com/doc/refman/8.4/en/enum.html
```
An enumeration value can also be the empty string ('') or NULL under certain circumstances:

If you insert an invalid value into an ENUM (that is, a string not present in the list of permitted values), the empty string is inserted instead as a special error value. This string can be distinguished from a “normal” empty string by the fact that this string has the numeric value 0. See [Index Values for Enumeration Literals](https://dev.mysql.com/doc/refman/8.4/en/enum.html#enum-indexes) for details about the numeric indexes for the enumeration values.
If strict SQL mode is enabled, attempts to insert invalid ENUM values result in an error.

```
OLake catches this situation but generates this error and fails:
"invalid ENUM value detected for column source: index 0 indicates an error value (empty string) from MySQL"
 

## Steps to reproduce
```
CREATE TABLE `enum_test` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `source` enum('OFFLINE','AVATAX','BUFFER','SKIPPED') DEFAULT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

SET SQL_MODE ='';

INSERT enum_test VALUES (1, 'OFFLINE');
INSERT enum_test VALUES (2, 'XYZ');
COMMIT;

#Run Olake here

INSERT enum_test VALUES (3, 'AVATAX');
INSERT enum_test VALUES (4, 'XYZ2');
COMMIT;

#Run Olake here with CDC

INSERT enum_test VALUES (5, 'BUFFER');
INSERT enum_test VALUES (6, NULL);
COMMIT;
```

## Expected behavior
Since its allowed behavior in MySQL OLake should put empty string into ENUM column and continue to read other records.

## Actual behavior
Fails with error
"invalid ENUM value detected for column source: index 0 indicates an error value (empty string) from MySQL"

### PR DESCRIPTION
**Pull request by vishalm0509**
# Description

sync invalid `ENUM` values as empty string

Fixes #876 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Scenario A
- [ ] Scenario B

# Screenshots or Recordings

## Documentation

- [ ] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [x] N/A (bug fix, refactor, or test changes only)

## Related PR's (If Any):

### CODE REVIEW

File: pkg/binlog/filter.go [hunk 1]
```diff
@@ -129,10 +129,12 @@ func convertRowToMap(row []interface{}, tableMap *replication.TableMapEvent, col
 				// for an update CDC event, the key of enum value is passed in binlog events which is always in int64
 				// during such a case, we need to find out the enum value of it from the index
 				if idx, isInt64 := val.(int64); isInt64 {
+					// MySQL stores invalid ENUM inserts as index 0 (special error value), which maps to empty string.
 					if idx == 0 {
-						return nil, fmt.Errorf("invalid ENUM value detected for column %s: index 0 indicates an error value (empty string) from MySQL", columns[i])
+						val = ""
+					} else {
+						val = enumValues[idx-1]
```
Comment (vikaxsh) [inline pkg/binlog/filter.go:135]: can we remove if else here?
example:
```
if tableMap.IsEnumColumn(i) && val != nil {
			if enumValues, ok := enumMap[i]; ok {
				indexedEnumValues := append([]string{""}, enumValues...)
				// Binlog update events pass ENUM values as int64 indices.
				if idx, isInt64 := val.(int64); isInt64 && idx >= 0 && idx < int64(len(indexedEnumValues)) {
					val = indexedEnumValues[idx]
				}
			}
		}
```
