### PR TITLE
fix: Mongodb username requirement 

### LINKED ISSUE #107: Username required in config.json while is optional while creating a Mongo cluster
## Problem

I was following the [Getting started](https://olake.io/docs/getting-started) doc and have the _config.json_ as below:

`{
    "hosts": [
      "localhost:27017",
      "localhost:27018",
      "localhost:27019"
    ],
    "replica-set": "rs0",
    "read-preference": "secondaryPreferred",
    "srv": false,
    "server-ram": 16,
    "database": "reddit",
    "max_threads": 50,
    "default_mode": "cdc",
    "backoff_retry_count": 2
  }`

Now, while generating the catalog file using command mentioned [here](https://olake.io/docs/getting-started#step-2-generate-a-catalog-file), I'm getting an error that says: 
 _FATAL error validating uri: username required if URI contains user info_ .

I have a MongoDB cluster without creds. Hence the field must be optional, as its not letting me create the catalog file.

### PR DESCRIPTION
**Pull request by TheCoderAdi**
# Description

This pull request includes a significant change to the `drivers/mongodb/internal/config.go` file. The change refactors the way MongoDB URIs are constructed, specifically handling authentication credentials more securely and clearly.

The most important changes include:

* [`drivers/mongodb/internal/config.go`](diffhunk://#diff-e0f35ec5e83200b90cb443fa8386951ea751f29512725dd51e8fd1d03dc90de5R49-R58): Added a new section to handle authentication credentials separately, using a ternary utility function to format the credentials string. This improves the readability and security of the URI construction.

Fixes #107 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

1. Use the following `config.json` without username/password:
   ```json
   {
      "hosts": ["localhost:27017", "localhost:27018", "localhost:27019"],
      "replica_set": "rs0",
      "read_preference": "secondaryPreferred",
      "srv": false,
      "server_ram": 16,
      "database": "reddit",
      "max_threads": 50,
      "default_mode": "cdc",
      "backoff_retry_count": 2
   }
   ```
2. Attempt to generate the catalog file using the command:
   https://olake.io/docs/getting-started/mongodb#step-2-generate-a-catalog-file
  Mentioned here

3. Previously, it would throw an error requiring a username. After this fix, the connection should work as expected without authentication.

### CODE REVIEW

**Comment by TheCoderAdi** [comment]
Hello @shubham19may ,

Could you please review the PR  
I have verified my commits.

**Comment by hash-data** [comment]
Hi @TheCoderAdi  thanks for opening a PR, will review it.

File: drivers/mongodb/internal/config.go [hunk 1]
```diff
@@ -46,9 +46,16 @@ func (c *Config) URI() string {
...
+	if c.Username != "" {
+		auth = utils.Ternary(c.Password != "", fmt.Sprintf("%s:%s@", c.Username, c.Password), fmt.Sprintf("%s@", c.Username)).(string)
+	}
+
+	// Final MongoDB URI
 	return fmt.Sprintf(
-		"%s://%s:%s@%s/?%s", connectionPrefix,
-		c.Username, c.Password, strings.Join(c.Hosts, ","), options,
+		"%s://%s%s/%s",
+		connectionPrefix, auth, strings.Join(c.Hosts, ","), options,
```
Comment (hash-data) [inline drivers/mongodb/internal/config.go:58]: what will happen in auth empty case, have you tested that as well?

Comment (TheCoderAdi) [reply drivers/mongodb/internal/config.go:58]: I just missed out. but I've now reviewed the code and verified that it correctly handles all cases. Can you please review it and let me know if you spot any issues?

File: drivers/mongodb/internal/config.go [hunk 2]
```diff
@@ -46,9 +46,16 @@ func (c *Config) URI() string {
 		options = fmt.Sprintf("%s&replicaSet=%s&readPreference=%s", options, c.ReplicaSet, c.ReadPreference)
 	}
 
+	//  Handle auth credentials
+	auth := ""
+	if c.Username != "" {
+		auth = utils.Ternary(c.Password != "", c.Username+":"+c.Password+"@", c.Username+"@").(string)
+	}
```
Comment (hash-data) [inline drivers/mongodb/internal/config.go:53]: can you use fm.Sprtintf instead of +

**Review by hash-data — APPROVED** [review]
