### PR TITLE
fix: stabilize uniqueidentifier chunk boundaries and CDC capture instance management

### LINKED ISSUE #780: MSSQL CDC: robust schema-evolution handling across capture instance create/drop
**Problem**  
In MSSQL CDC, schema changes on a source table are not automatically reflected in the existing capture instance.  
As a result, users currently need to manually handle capture-instance lifecycle steps whenever schema evolves (create new capture instance, coordinate transition, and manage old instance cleanup).

**This introduces**:
- operational overhead for users,
- higher risk of human error during CDC continuity handling,
- poor UX for long-running pipelines where schema changes are common.

**Current Pain Point**  
For schema evolution workflows, users must intervene with manual MSSQL CDC operations instead of OLake handling it as part of normal replication behavior.

**Good to Have**
- OLake should be able to manage schema-evolution lifecycle for MSSQL CDC automatically as an optional advanced capability.
- Users should not need manual DBA-style steps for routine schema changes.
- The experience should be predictable and safe across capture-instance transitions (creation/switch/cleanup).
- Clear observability/logging around schema-evolution events is desirable.
- Final design/approach is yet to be decided.

### PR DESCRIPTION
**Pull request by vishalm0509**
# Description

Fixes #780 (issue) 

## Type of change

**This PR improves MSSQL sync stability in two areas:**
- fixes chunk boundary handling for `uniqueidentifier` primary keys by normalizing GUID byte values before chunk split/scan logic
- adds optional CDC capture-instance lifecycle management (manage_capture_instances) to better handle schema evolution and stale instances

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Scenario A
- [ ] Scenario B

# Screenshots or Recordings

## Documentation

- [x] Documentation Link: [link to README, olake.io/docs, or olake-docs]
- [X] N/A (bug fix, refactor, or test changes only)

## Related PR's (If Any):

### CODE REVIEW

File: drivers/mssql/internal/backfill.go [hunk 1]
```diff
@@ -124,9 +124,8 @@ func (m *MSSQL) GetOrSplitChunks(ctx context.Context, pool *destination.WriterPo
 			if len(pkCols) == 0 {
 				return nil
 			}
-
 			// Get the minimum and maximum values for the primary key columns
-			minVal, maxVal, err := m.getTableExtremesMSSQL(ctx, stream, pkCols, tx)
+			minVal, maxVal, columnTypes, err := m.getTableExtremesMSSQL(ctx, stream, pkCols, tx)
```
Comment (vikaxsh) [inline drivers/mssql/internal/backfill.go]: shouldn't we fetch type from column definition

File: drivers/mssql/internal/backfill.go [hunk 2]
```diff
@@ -135,21 +134,39 @@ func (m *MSSQL) GetOrSplitChunks(ctx context.Context, pool *destination.WriterPo
 				return nil
 			}
 
+			// QUESTION: Should we handle Binary data types as a part of composite key?
+			normalizeBoundaryValue := func(value any) string {
```
Comment (vikaxsh) [inline drivers/mssql/internal/backfill.go]: move this function outside of this function, can be reuse in future and can add more datatype support

File: drivers/mssql/internal/cdc.go [hunk 3]
```diff
@@ -194,6 +170,138 @@ func (m *MSSQL) PostCDC(ctx context.Context, streamIndex int) error {
...
+			return fmt.Errorf("failed to scan DDL history: %w", err)
+		}
+		streamID := fmt.Sprintf("%s.%s", schema, table)
+		// Since results are ORDER BY ASC, the last one for a table is the latest.
+		latestDDLMap[streamID] = hex.EncodeToString(ddlLSN)
+	}
+	if err := rows.Err(); err != nil {
+		return fmt.Errorf("error iterating over bulk DDL history: %w", err)
+	}
+	rows.Close()
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]: dead code

File: drivers/mssql/internal/cdc.go [hunk 4]
```diff
@@ -194,6 +170,138 @@ func (m *MSSQL) PostCDC(ctx context.Context, streamIndex int) error {
...
+// prepareCaptureInstancesBulk retrieves all currently defined CDC capture instances for the specified streams.
+func (m *MSSQL) prepareCaptureInstancesBulk(ctx context.Context, streamIDs []string) (map[string][]captureInstance, error) {
+	rows, err := m.client.QueryContext(ctx, jdbc.MSSQLCDCDiscoverQuery(streamIDs))
+	if err != nil {
+		return nil, fmt.Errorf("failed to query MSSQL CDC tables: %s", err)
+	}
+	defer rows.Close()
+
+	captureInstances := make(map[string][]captureInstance)
+	for rows.Next() {
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go:173]: don't we need to check rows.Err here?

File: drivers/mssql/internal/cdc.go [hunk 5]
```diff
@@ -130,25 +115,16 @@ func (m *MSSQL) StreamChanges(ctx context.Context, streamIndex int, processFn ab
...
-		// Skip if this capture started after fromLSN
-		if captureInstances[captureIdx].startLSN > lsnInState {
-			continue
-		}
-
-		// Select the capture instance
-		selectedCapture = &captureInstances[captureIdx]
+	captureIdx, selectedCapture := newestValidInstance(captureInstances, lsnInState)
 
+	if selectedCapture != nil {
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]: can u move this below selectedCapture == nil

File: drivers/mssql/internal/cdc.go [hunk 6]
```diff
@@ -73,22 +43,39 @@ func (m *MSSQL) PreCDC(ctx context.Context, streams []types.StreamInterface) err
...
 			m.state.SetCursor(stream.Self(), cdcCursorKey, currentLSN)
+			streamLSNMap[stream.ID()] = currentLSN
+		} else {
+			streamLSNMap[stream.ID()] = lsnVal.(string)
+		}
+	}
+
+	// Manage capture instance creation and deletion
+	if m.config.ManageCaptureInstances {
+		if err := m.manageCaptureInstances(ctx, streams, streamLSNMap, captureInstancesMap); err != nil {
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]: can we pass streamIDs here instead of streams

File: drivers/mssql/internal/cdc.go [hunk 7]
```diff
@@ -73,22 +43,39 @@ func (m *MSSQL) PreCDC(ctx context.Context, streams []types.StreamInterface) err
...
+	}
+
+	// Bulk discovery of capture instances for validation and management
+	captureInstancesMap, err := m.prepareCaptureInstancesBulk(ctx, streamIDs)
+	if err != nil {
+		return fmt.Errorf("failed to discover capture instances: %w", err)
+	}
 
-		if !enabled {
+	streamLSNMap := make(map[string]string)
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]: can avoid computing streamLSNMap, and directly read lSN from state in manageCaptureInstances

File: drivers/mssql/internal/cdc.go [hunk 8]
```diff
@@ -73,22 +43,39 @@ func (m *MSSQL) PreCDC(ctx context.Context, streams []types.StreamInterface) err
...
+		if lsnVal == nil {
 			m.state.SetCursor(stream.Self(), cdcCursorKey, currentLSN)
+			streamLSNMap[stream.ID()] = currentLSN
+		} else {
+			streamLSNMap[stream.ID()] = lsnVal.(string)
+		}
+	}
+
+	// Manage capture instance creation and deletion
+	if m.config.ManageCaptureInstances {
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]: move this check inside the function

File: drivers/mssql/internal/cdc.go [hunk 9]
```diff
@@ -73,22 +43,39 @@ func (m *MSSQL) PreCDC(ctx context.Context, streams []types.StreamInterface) err
 		return fmt.Errorf("failed to get MSSQL current max LSN: %w", err)
 	}
 
-	// check if CDC is enabled for each stream
-	for _, stream := range streams {
-		enabled, err := m.validateCDCStream(ctx, stream.Namespace(), stream.Name())
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go:78]: remove validateCDCStream if we are no longer using that

File: drivers/mssql/internal/backfill.go (hunk 1 above)
Comment (vishalm0509) [reply drivers/mssql/internal/backfill.go]: Right, made changes

File: drivers/mssql/internal/backfill.go (hunk 2 above)
Comment (vishalm0509) [reply drivers/mssql/internal/backfill.go]: Done

File: drivers/mssql/internal/cdc.go (hunk 3 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: 👀 Done

File: drivers/mssql/internal/cdc.go (hunk 4 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go:173]: We need to. Added

File: drivers/mssql/internal/cdc.go (hunk 5 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: Done

File: drivers/mssql/internal/cdc.go (hunk 6 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: That's a nice idea. Done

File: drivers/mssql/internal/cdc.go (hunk 9 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go:78]: Done

File: drivers/mssql/internal/cdc.go (hunk 8 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: Done

File: drivers/mssql/internal/cdc.go (hunk 7 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: Done

File: drivers/mssql/internal/backfill.go [hunk 10]
```diff
@@ -135,21 +135,33 @@ func (m *MSSQL) GetOrSplitChunks(ctx context.Context, pool *destination.WriterPo
 				return nil
 			}
 
+			columnTypes := make(map[string]string)
+			if len(pkCols) == 1 {
+				columnTypes, err = m.getColumnTypesMSSQL(ctx, stream, tx)
+				if err != nil {
+					return fmt.Errorf("failed to get table column types: %s", err)
+				}
+			}
```
Comment (vikaxsh) [inline drivers/mssql/internal/backfill.go]: We could move the fetching of `columnTypes` inside `normalizeBoundaryValue`, since it’s only used there. That would also remove the redundant check for the PK length.

File: drivers/mssql/internal/backfill.go [hunk 11]
```diff
@@ -269,8 +281,75 @@ func (m *MSSQL) GetOrSplitChunks(ctx context.Context, pool *destination.WriterPo
 	return chunks, err
 }
 
+// getColumnTypesMSSQL returns SQL data types keyed by lower-cased column name.
+func (m *MSSQL) getColumnTypesMSSQL(ctx context.Context, stream types.StreamInterface, tx *sql.Tx) (map[string]string, error) {
```
Comment (vikaxsh) [inline drivers/mssql/internal/backfill.go]: instead of fetching columnType for all column can we fetch one pK would be more efficient

File: drivers/mssql/internal/cdc.go [hunk 12]
```diff
@@ -73,22 +43,33 @@ func (m *MSSQL) PreCDC(ctx context.Context, streams []types.StreamInterface) err
...
+		return fmt.Errorf("failed to discover capture instances: %w", err)
+	}
 
-		if !enabled {
+	for _, stream := range streams {
+		if _, found := captureInstancesMap[stream.ID()]; !found {
 			return fmt.Errorf("CDC is not enabled for stream %s.%s", stream.Namespace(), stream.Name())
 		}
 
-		// Initialize LSN for each stream if not present
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go:87]: add this comment again

File: drivers/mssql/internal/cdc.go [hunk 13]
```diff
@@ -194,6 +160,148 @@ func (m *MSSQL) PostCDC(ctx context.Context, streamIndex int) error {
...
+		}
+		streamID := fmt.Sprintf("%s.%s", schema, table)
+		// Since results are ORDER BY ASC, the last one for a table is the latest.
+		latestDDLMap[streamID] = hex.EncodeToString(ddlLSN)
+	}
+	if err := rows.Err(); err != nil {
+		return fmt.Errorf("error iterating over bulk DDL history: %w", err)
+	}
+
+	for _, streamID := range streamIDs {
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]: can we map over streams instead of streamIDs, eliminates the entire streamByID map construction

File: drivers/mssql/internal/cdc.go [hunk 14]
```diff
@@ -194,6 +160,148 @@ func (m *MSSQL) PostCDC(ctx context.Context, streamIndex int) error {
...
+
+	// Fetch DDL history for all streams in bulk
+	ddlHistoryQuery := jdbc.MSSQLCDCGetDDLHistoryBulkQuery(streamIDs)
+	rows, err := m.client.QueryContext(ctx, ddlHistoryQuery)
+	if err != nil {
+		return fmt.Errorf("failed to query bulk DDL history: %w", err)
+	}
+	defer rows.Close()
+
+	latestDDLMap := make(map[string]string)
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]:
```suggestion
latestDDLMap := make(map[string]string, len(streamIDs))
```

File: drivers/mssql/internal/cdc.go [hunk 15]
```diff
@@ -194,6 +160,148 @@ func (m *MSSQL) PostCDC(ctx context.Context, streamIndex int) error {
...
 
+// prepareCaptureInstancesBulk retrieves all currently defined CDC capture instances for the specified streams.
+func (m *MSSQL) prepareCaptureInstancesBulk(ctx context.Context, streamIDs []string) (map[string][]captureInstance, error) {
+	rows, err := m.client.QueryContext(ctx, jdbc.MSSQLCDCDiscoverQuery(streamIDs))
+	if err != nil {
+		return nil, fmt.Errorf("failed to query MSSQL CDC tables: %s", err)
+	}
+	defer rows.Close()
+
+	captureInstances := make(map[string][]captureInstance)
```
Comment (vikaxsh) [inline drivers/mssql/internal/cdc.go]:
```suggestion
	captureInstances := make(map[string][]captureInstance, len(streamIDs))
```

File: drivers/mssql/internal/backfill.go (hunk 10 above)
Comment (vishalm0509) [reply drivers/mssql/internal/backfill.go]: We call normalizeBoundary value multiple times and each time it will query the database then.

File: drivers/mssql/internal/cdc.go (hunk 12 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go:87]: Done

File: drivers/mssql/internal/backfill.go (hunk 10 above)
Comment (vikaxsh) [reply drivers/mssql/internal/backfill.go]: yeah, correct lets not do that

File: drivers/mssql/internal/backfill.go (hunk 11 above)
Comment (vishalm0509) [reply drivers/mssql/internal/backfill.go]: To do this we need to add a new query function, and the performance benefits is almost negligible. I think we can leave it as is.

File: drivers/mssql/internal/cdc.go (hunk 13 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: Done

File: drivers/mssql/internal/cdc.go (hunk 14 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: Done

File: drivers/mssql/internal/cdc.go (hunk 15 above)
Comment (vishalm0509) [reply drivers/mssql/internal/cdc.go]: D\one

File: drivers/mssql/internal/backfill.go (hunk 11 above)
Comment (vikaxsh) [reply drivers/mssql/internal/backfill.go]: we can add a new query function, we should fetch for the column we require

Comment (vishalm0509) [reply drivers/mssql/internal/backfill.go]: Done
